services:
  postgres:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product
      CARGO_HOME: /usr/local/cargo
    working_dir: /morpheme_funcs
    ports:
      - "5432:5432"
    volumes:
      - ../:/morpheme_funcs
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
      # ワイルドカードによる指定だとうまくいかないので、明示的に指定
      - ./sql/inserts/anzenyouhin.sql:/docker-entrypoint-initdb.d/02_anzenyouhin.sql
      - ./sql/inserts/buturyuhokan.sql:/docker-entrypoint-initdb.d/03_buturyuhokan.sql
      - ./sql/inserts/chemical_product.sql:/docker-entrypoint-initdb.d/04_chemical_product.sql
      - ./sql/inserts/cutting_tool_product.sql:/docker-entrypoint-initdb.d/05_cutting_tool_product.sql
      - ./sql/inserts/electronic_product.sql:/docker-entrypoint-initdb.d/06_electronic_product.sql
      - ./sql/inserts/hansoukiki.sql:/docker-entrypoint-initdb.d/07_hansoukiki.sql
      - ./sql/inserts/hardware_materials_product.sql:/docker-entrypoint-initdb.d/08_hardware_materials_product.sql
      - ./sql/inserts/kojisyomei.sql:/docker-entrypoint-initdb.d/09_kojisyomei.sql
      - ./sql/inserts/konpouyouhin.sql:/docker-entrypoint-initdb.d/10_konpouyouhin.sql
      - ./sql/inserts/machine_tool_product.sql:/docker-entrypoint-initdb.d/11_machine_tool_product.sql
      - ./sql/inserts/measuring_tool_product.sql:/docker-entrypoint-initdb.d/12_measuring_tool_product.sql
      - ./sql/inserts/mechatronics_product.sql:/docker-entrypoint-initdb.d/13_mechatronics_product.sql
      - ./sql/inserts/niyakuyouhin.sql:/docker-entrypoint-initdb.d/14_niyakuyouhin.sql
      - ./sql/inserts/pneumatic_product.sql:/docker-entrypoint-initdb.d/15_pneumatic_product.sql
      - ./sql/inserts/power_tools_product.sql:/docker-entrypoint-initdb.d/16_power_tools_product.sql
      - ./sql/inserts/seisoeisei.sql:/docker-entrypoint-initdb.d/17_seisoeisei.sql
      - ./init-morpheme.sh:/docker-entrypoint-initdb.d/18_init-morpheme.sh
      - postgres_data:/var/lib/postgresql/data

# 永続化のためにボリュームを定義
volumes:
  postgres_data:
