INSERT INTO product (name) VALUES
    ('セキュア Ethernet 通信モジュール アンテナ内蔵 メッシュネットワーク対応 Smart-1467A'),
    ('セキュア Bluetooth 通信モジュール アンテナ内蔵 メッシュネットワーク対応 VCCI Class B Pro-8335S'),
    ('RISC-V 省電力 マイコン 16bit GPIO 32pin Embedded-6645A'),
    ('近接 デジタル出力 センサーモジュール 小型3mm角 サンプリング10kHz REACH対応 長寿命設計 Embedded-5007A'),
    ('リニア 昇降圧型 電源IC 出力1A スタンバイ機能付'),
    ('LDO 昇降圧型 電源IC QFN 効率98%'),
    ('据置 パワーメータ デジタル計測器 チャンネル2CH サンプリング1GS/s'),
    ('絶縁 DisplayPort インターフェース Ver2.0 サージ保護付 IoT-2108R'),
    ('ジャイロ アナログ出力 センサーモジュール 超小型2mm角 低消費電力1mA以下 Advanced-6980B'),
    ('高速 HDMI インターフェース Ver3.0 ホットプラグ対応 Embedded-9093B'),
    ('近接 高精度 センサーモジュール 1.8V動作 低消費電力1mA以下 EMC対策済'),
    ('AC-DC 同期整流 電源IC 出力3A 効率98% FCC認証取得 IoT-8819S'),
    ('リニア 昇圧型 電源IC 出力3A 効率95% Industrial-3392C'),
    ('セキュア WiFi 通信モジュール 外付け マルチプロトコル対応 Industrial-4613C'),
    ('ベンチトップ スペアナ デジタル計測器 8CH メモリ長1M'),
    ('IoT WiFi 通信モジュール 1Gbps メッシュネットワーク対応'),
    ('産業用 HDMI インターフェース Ver2.0 ホットプラグ対応'),
    ('RISC-V 組込み向け マイコン 200MHz GPIO 100pin FCC認証取得'),
    ('DC-DC 昇圧型 電源IC 出力3A スタンバイ機能付 EMC対策済'),
    ('無線 Ethernet 通信モジュール アンテナ内蔵 セキュリティ機能搭載 CE認証取得 Pro-4823C'),
    ('環境 SPI接続 センサーモジュール 5V動作 サンプリング1kHz RoHS対応 Embedded-6978C'),
    ('スイッチング 絶縁型 電源IC QFN スタンバイ機能付 長寿命設計 Pro-4627S'),
    ('LDO 同期整流 電源IC QFN スタンバイ機能付 REACH対応 Advanced-4768B'),
    ('据置 ロジアナ デジタル計測器 4CH メモリ長1M Smart-7778B'),
    ('ARM Cortex-M マイコン 16bit メモリ256KB VCCI Class B'),
    ('温湿度 アナログ出力 センサーモジュール 5V動作 サンプリング1kHz RoHS対応 Embedded-7470A'),
    ('セキュア WiFi 通信モジュール 1Gbps 暗号化機能付 EMC対策済'),
    ('ノイズ対策 DisplayPort インターフェース Gen5 ホットプラグ対応 RoHS対応'),
    ('絶縁 DisplayPort インターフェース Ver2.0 サージ保護付 Smart-4943R'),
    ('ポータブル スペアナ デジタル計測器 チャンネル2CH 4GS/s Pro-4775C'),
    ('環境 高精度 センサーモジュール 5V動作 サンプリング1kHz Pro-7475A'),
    ('無線 RS485 通信モジュール 1Gbps マルチプロトコル対応 VCCI Class B'),
    ('高速 UART インターフェース Gen3 ホットプラグ対応 Advanced-2346S'),
    ('ノイズ対策 USB インターフェース Ver2.0 サージ保護付'),
    ('産業用 デュアルコア マイコン 64bit メモリ256KB Industrial-6497R'),
    ('ポータブル パワーメータ デジタル計測器 帯域100MHz 4GS/s UL認証取得 Pro-6127B'),
    ('加速度 SPI接続 センサーモジュール 3.3V動作 分解能16bit UL認証取得 Embedded-6317C'),
    ('有線 RS485 通信モジュール 10Gbps マルチプロトコル対応 EMC対策済 Smart-6845B'),
    ('ARM 省電力 マイコン 16bit メモリ256KB CE認証取得 省電力設計 Embedded-1503R'),
    ('温湿度 I2C接続 センサーモジュール 5V動作 分解能16bit Embedded-1617C'),
    ('環境 I2C接続 センサーモジュール 5V動作 サンプリング10kHz Industrial-5801R'),
    ('スイッチング 降圧型 電源IC DIP 効率98% Advanced-4636B'),
    ('AC-DC 降圧型 電源IC 出力3A 保護回路内蔵 REACH対応 Smart-5583C'),
    ('絶縁 HDMI インターフェース Gen5 オートネゴシエーション'),
    ('DC-DC 昇圧型 電源IC 出力1A スタンバイ機能付 CE認証取得 Pro-6671C'),
    ('加速度 高精度 センサーモジュール 超小型2mm角 サンプリング10kHz UL認証取得'),
    ('有線 Ethernet 通信モジュール 通信速度100Mbps 暗号化機能付 Pro-2263A'),
    ('ベンチトップ オシロスコープ デジタル計測器 帯域200MHz 4GS/s Advanced-7602C'),
    ('近接 I2C接続 センサーモジュール 1.8V動作 サンプリング10kHz UL認証取得 Pro-3786C'),
    ('ポータブル オシロスコープ デジタル計測器 8CH 4M'),
    ('RISC-V 省電力 マイコン 64bit GPIO 100pin REACH対応'),
    ('IoT Bluetooth 通信モジュール 1Gbps 暗号化機能付 高信頼性 Industrial-6548S'),
    ('AC-DC 昇降圧型 電源IC 出力3A 効率95% Advanced-6167S'),
    ('有線 WiFi 通信モジュール 10Gbps メッシュネットワーク対応'),
    ('ノイズ対策 UART インターフェース Gen5 ESD保護機能付 REACH対応 長寿命設計 Industrial-3257S'),
    ('セキュア Bluetooth 通信モジュール 1Gbps セキュリティ機能搭載'),
    ('ARM 省電力 マイコン 400MHz GPIO 32pin 省電力設計 Smart-4468R'),
    ('DC-DC 降圧型 電源IC 出力5A 入力範囲4-60V Pro-9080S'),
    ('ジャイロ 高精度 センサーモジュール 3.3V動作 低消費電力1mA以下'),
    ('環境 デジタル出力 センサーモジュール 超小型2mm角 サンプリング10kHz CE認証取得'),
    ('ジャイロ SPI接続 センサーモジュール 3.3V動作 サンプリング1kHz EMC対策済'),
    ('リニア 降圧型 電源IC 出力5A 効率98% FCC認証取得 IoT-4865R'),
    ('車載用 Cortex-M マイコン クロック周波数100MHz メモリ256KB IoT-2429C'),
    ('ポータブル ロジアナ デジタル計測器 4CH 2M Embedded-2984B'),
    ('産業用 組込み向け マイコン 400MHz GPIO 64pin 長寿命設計 Advanced-3046B'),
    ('IoT Bluetooth 通信モジュール 1Gbps 暗号化機能付 RoHS対応 長寿命設計 Embedded-1599R'),
    ('スイッチング 降圧型 電源IC 出力1A スタンバイ機能付 ノイズ耐性強化 Smart-7573S'),
    ('LDO 降圧型 電源IC QFN 効率98% VCCI Class B 長寿命設計 Embedded-6134S'),
    ('ARM 組込み向け マイコン クロック周波数100MHz メモリ1MB'),
    ('ハンディ パワーメータ デジタル計測器 帯域100MHz 4GS/s Industrial-7680R'),
    ('AVR 高性能 マイコン クロック周波数100MHz メモリ512KB'),
    ('近接 デジタル出力 センサーモジュール 5V動作 低消費電力1mA以下'),
    ('産業用 RS485 通信モジュール 10Gbps メッシュネットワーク対応 IoT-1643B'),
    ('AC-DC 昇降圧型 電源IC DIP 入力範囲4-60V EMC対策済 Smart-4201R'),
    ('ジャイロ 高精度 センサーモジュール 5V動作 分解能24bit IoT-6170B'),
    ('ARM 組込み向け マイコン クロック周波数100MHz GPIO 64pin IoT-7482C'),
    ('ベンチトップ マルチメータ デジタル計測器 帯域200MHz メモリ長1M Embedded-7833R'),
    ('車載用 省電力 マイコン クロック周波数100MHz メモリ1MB CE認証取得'),
    ('堅牢 HDMI インターフェース Ver3.0 サージ保護付 Embedded-5417C'),
    ('DC-DC 同期整流 電源IC QFN 効率95% ノイズ耐性強化 Smart-3881R'),
    ('LDO 絶縁型 電源IC 出力5A 効率95%'),
    ('ポータブル スペアナ デジタル計測器 500MHz サンプリング1GS/s Industrial-3968A'),
    ('RISC-V デュアルコア マイコン 400MHz メモリ1MB CE認証取得 Smart-2306A'),
    ('産業用 HDMI インターフェース Ver3.0 ESD保護機能付'),
    ('据置 スペアナ デジタル計測器 チャンネル2CH 4GS/s Embedded-1101C'),
    ('ベンチトップ スペアナ デジタル計測器 帯域100MHz 2M Smart-7389S'),
    ('RISC-V Cortex-M マイコン 200MHz メモリ1MB Embedded-8970R'),
    ('DC-DC 昇降圧型 電源IC DIP スタンバイ機能付 CE認証取得'),
    ('産業用 PCIe インターフェース Gen5 ESD保護機能付 Embedded-3889S'),
    ('ハンディ マルチメータ デジタル計測器 500MHz 4GS/s FCC認証取得 Embedded-1961R'),
    ('無線 Ethernet 通信モジュール 1Gbps マルチプロトコル対応 UL認証取得 長寿命設計'),
    ('車載用 組込み向け マイコン 32bit GPIO 64pin'),
    ('IoT WiFi 通信モジュール 1Gbps セキュリティ機能搭載 REACH対応'),
    ('ノイズ対策 UART インターフェース Gen5 オートネゴシエーション 高信頼性'),
    ('高機能 ロジアナ デジタル計測器 帯域200MHz メモリ長1M CE認証取得'),
    ('ノイズ対策 UART インターフェース Gen3 ホットプラグ対応 高信頼性'),
    ('ベンチトップ オシロスコープ デジタル計測器 帯域100MHz 4M 高信頼性'),
    ('LDO 絶縁型 電源IC 出力5A 入力範囲4-60V REACH対応 Smart-6496A'),
    ('車載用 高性能 マイコン 64bit GPIO 100pin REACH対応 Embedded-2433R'),
    ('DC-DC 絶縁型 電源IC 出力5A 保護回路内蔵 RoHS対応 省電力設計 Smart-6238C'),
    ('RISC-V Cortex-M マイコン クロック周波数100MHz GPIO 64pin'),
    ('産業用 USB インターフェース Gen5 ESD保護機能付'),
    ('据置 オシロスコープ デジタル計測器 500MHz サンプリング1GS/s FCC認証取得'),
    ('DC-DC 昇圧型 電源IC 出力3A スタンバイ機能付 VCCI Class B Embedded-4659A'),
    ('無線 RS485 通信モジュール アンテナ内蔵 メッシュネットワーク対応 REACH対応'),
    ('産業用 DisplayPort インターフェース Gen5 オートネゴシエーション UL認証取得 Industrial-2796A'),
    ('高機能 スペアナ デジタル計測器 帯域200MHz 4GS/s'),
    ('堅牢 HDMI インターフェース Ver2.0 サージ保護付 省電力設計 Industrial-6824S'),
    ('ノイズ対策 DisplayPort インターフェース Gen4 ホットプラグ対応'),
    ('無線 CAN 通信モジュール 1Gbps マルチプロトコル対応 UL認証取得 高信頼性'),
    ('IoT WiFi 通信モジュール 1Gbps セキュリティ機能搭載 CE認証取得'),
    ('AVR デュアルコア マイコン 200MHz メモリ1MB 省電力設計'),
    ('ポータブル マルチメータ デジタル計測器 8CH サンプリング1GS/s'),
    ('RISC-V Cortex-M マイコン 64bit メモリ256KB FCC認証取得'),
    ('加速度 SPI接続 センサーモジュール 5V動作 サンプリング1kHz IoT-9024A'),
    ('産業用 CAN 通信モジュール アンテナ内蔵 セキュリティ機能搭載'),
    ('IoT WiFi 通信モジュール アンテナ内蔵 マルチプロトコル対応 FCC認証取得 EMC対策済 Embedded-8608A'),
    ('ポータブル パワーメータ デジタル計測器 8CH 4GS/s REACH対応'),
    ('無線 WiFi 通信モジュール アンテナ内蔵 セキュリティ機能搭載'),
    ('高機能 オシロスコープ デジタル計測器 4CH メモリ長1M EMC対策済'),
    ('有線 WiFi 通信モジュール 外付け メッシュネットワーク対応'),
    ('ポータブル マルチメータ デジタル計測器 帯域200MHz サンプリング1GS/s IoT-7857R'),
    ('無線 Bluetooth 通信モジュール 1Gbps セキュリティ機能搭載'),
    ('高速 USB インターフェース Gen5 ホットプラグ対応 EMC対策済 IoT-7242C'),
    ('有線 Ethernet 通信モジュール 外付け マルチプロトコル対応'),
    ('無線 CAN 通信モジュール 通信速度100Mbps マルチプロトコル対応 RoHS対応 Pro-3667C'),
    ('絶縁 USB インターフェース Ver3.0 ホットプラグ対応 CE認証取得 高信頼性'),
    ('高速 HDMI インターフェース Gen5 ESD保護機能付'),
    ('産業用 DisplayPort インターフェース Gen4 オートネゴシエーション'),
    ('産業用 組込み向け マイコン 200MHz GPIO 32pin Industrial-3083A'),
    ('温湿度 アナログ出力 センサーモジュール 3.3V動作 低消費電力1mA以下 REACH対応 高信頼性 Industrial-3177A'),
    ('加速度 高精度 センサーモジュール 3.3V動作 サンプリング10kHz ノイズ耐性強化 Pro-8928B'),
    ('ハンディ パワーメータ デジタル計測器 チャンネル2CH 4M'),
    ('環境 アナログ出力 センサーモジュール 1.8V動作 分解能16bit'),
    ('産業用 CAN 通信モジュール 通信速度100Mbps 暗号化機能付 Embedded-3438S'),
    ('産業用 UART インターフェース Ver2.0 オートネゴシエーション CE認証取得 Industrial-1839R'),
    ('スイッチング 同期整流 電源IC パッケージSOP 効率98%'),
    ('ポータブル パワーメータ デジタル計測器 帯域200MHz 2M REACH対応'),
    ('産業用 Bluetooth 通信モジュール アンテナ内蔵 メッシュネットワーク対応'),
    ('産業用 Ethernet 通信モジュール 1Gbps メッシュネットワーク対応 高信頼性'),
    ('ARM Cortex-M マイコン 32bit GPIO 32pin IoT-3286S'),
    ('有線 Ethernet 通信モジュール 10Gbps 暗号化機能付'),
    ('ノイズ対策 HDMI インターフェース Gen3 ESD保護機能付 VCCI Class B 長寿命設計'),
    ('産業用 DisplayPort インターフェース Gen3 オートネゴシエーション Advanced-3552A'),
    ('近接 アナログ出力 センサーモジュール 超小型2mm角 サンプリング10kHz Pro-6627C'),
    ('セキュア Ethernet 通信モジュール 1Gbps メッシュネットワーク対応 Advanced-9519C'),
    ('産業用 USB インターフェース Ver2.0 サージ保護付 ノイズ耐性強化 Embedded-3008B'),
    ('DC-DC 昇降圧型 電源IC DIP 入力範囲4-60V'),
    ('産業用 UART インターフェース Gen5 ホットプラグ対応 Smart-6264A'),
    ('セキュア WiFi 通信モジュール アンテナ内蔵 セキュリティ機能搭載 REACH対応 Smart-1981R'),
    ('環境 SPI接続 センサーモジュール 5V動作 分解能16bit RoHS対応 長寿命設計 Embedded-1300B'),
    ('ベンチトップ マルチメータ デジタル計測器 8CH 4GS/s Embedded-9771S'),
    ('RISC-V 省電力 マイコン 200MHz メモリ1MB Smart-6376C'),
    ('据置 ロジアナ デジタル計測器 チャンネル2CH サンプリング1GS/s ノイズ耐性強化 Pro-1266S'),
    ('リニア 昇圧型 電源IC 出力3A 保護回路内蔵'),
    ('高機能 オシロスコープ デジタル計測器 8CH 4M Embedded-2315C'),
    ('ARM Cortex-M マイコン 400MHz メモリ256KB'),
    ('ARM 省電力 マイコン 32bit GPIO 64pin Smart-5144A'),
    ('据置 スペアナ デジタル計測器 チャンネル2CH メモリ長1M Industrial-2528C'),
    ('温湿度 アナログ出力 センサーモジュール 小型3mm角 サンプリング1kHz Pro-3232A'),
    ('車載用 デュアルコア マイコン 16bit メモリ256KB'),
    ('産業用 RS485 通信モジュール 外付け メッシュネットワーク対応 FCC認証取得'),
    ('加速度 アナログ出力 センサーモジュール 超小型2mm角 分解能16bit EMC対策済 Embedded-8095C'),
    ('産業用 WiFi 通信モジュール 外付け メッシュネットワーク対応 REACH対応 省電力設計'),
    ('近接 I2C接続 センサーモジュール 1.8V動作 分解能16bit VCCI Class B Industrial-5878C'),
    ('RISC-V 組込み向け マイコン 32bit メモリ512KB Smart-2266S'),
    ('リニア 同期整流 電源IC QFN 効率95% VCCI Class B 長寿命設計 Industrial-2895S'),
    ('ポータブル パワーメータ デジタル計測器 4CH サンプリング1GS/s REACH対応'),
    ('加速度 SPI接続 センサーモジュール 5V動作 分解能24bit 長寿命設計'),
    ('産業用 Bluetooth 通信モジュール 10Gbps セキュリティ機能搭載 Embedded-3074A'),
    ('AVR Cortex-M マイコン 16bit GPIO 64pin REACH対応 Pro-5329C'),
    ('ノイズ対策 DisplayPort インターフェース Ver2.0 サージ保護付 VCCI Class B Embedded-8111B'),
    ('セキュア RS485 通信モジュール アンテナ内蔵 セキュリティ機能搭載 Embedded-2033S'),
    ('据置 ロジアナ デジタル計測器 500MHz 2GS/s Smart-8569S'),
    ('有線 WiFi 通信モジュール 外付け マルチプロトコル対応 Advanced-2152R'),
    ('絶縁 USB インターフェース Ver3.0 サージ保護付 Embedded-5081B'),
    ('高速 UART インターフェース Ver3.0 オートネゴシエーション IoT-8782R'),
    ('ノイズ対策 HDMI インターフェース Ver3.0 サージ保護付'),
    ('スイッチング 昇降圧型 電源IC 出力5A 効率98% Pro-8724C'),
    ('AVR 高性能 マイコン 200MHz メモリ512KB REACH対応 IoT-7307C'),
    ('車載用 高性能 マイコン 16bit GPIO 64pin Embedded-5045A'),
    ('DC-DC 降圧型 電源IC QFN 入力範囲4-60V CE認証取得 Advanced-9973S'),
    ('ノイズ対策 PCIe インターフェース Gen5 ホットプラグ対応 FCC認証取得 長寿命設計'),
    ('DC-DC 降圧型 電源IC パッケージSOP 効率95% Advanced-4897R'),
    ('堅牢 UART インターフェース Ver4.0 サージ保護付 IoT-4157R'),
    ('無線 Bluetooth 通信モジュール 10Gbps マルチプロトコル対応 Advanced-8584C'),
    ('産業用 PCIe インターフェース Gen4 サージ保護付'),
    ('リニア 降圧型 電源IC 出力3A スタンバイ機能付 Advanced-9487C'),
    ('DC-DC 絶縁型 電源IC パッケージSOP スタンバイ機能付'),
    ('高機能 ロジアナ デジタル計測器 8CH 4M VCCI Class B 高信頼性 Embedded-9064B'),
    ('産業用 CAN 通信モジュール 外付け 暗号化機能付 Pro-8099B'),
    ('ジャイロ I2C接続 センサーモジュール 1.8V動作 サンプリング1kHz Embedded-1243A'),
    ('ノイズ対策 DisplayPort インターフェース Gen3 ESD保護機能付 Industrial-9041R'),
    ('AC-DC 降圧型 電源IC QFN 保護回路内蔵 EMC対策済'),
    ('RISC-V Cortex-M マイコン 400MHz メモリ256KB'),
    ('ジャイロ I2C接続 センサーモジュール 超小型2mm角 サンプリング1kHz Smart-4563B'),
    ('無線 Ethernet 通信モジュール 外付け マルチプロトコル対応 Smart-1706R'),
    ('ジャイロ 高精度 センサーモジュール 5V動作 分解能24bit RoHS対応 Smart-9445C'),
    ('加速度 デジタル出力 センサーモジュール 1.8V動作 サンプリング10kHz VCCI Class B 高信頼性'),
    ('DC-DC 昇圧型 電源IC 出力3A 入力範囲4-60V UL認証取得'),
    ('無線 WiFi 通信モジュール 10Gbps 暗号化機能付 IoT-5210A'),
    ('産業用 Bluetooth 通信モジュール アンテナ内蔵 メッシュネットワーク対応 RoHS対応 Advanced-4915A'),
    ('産業用 Bluetooth 通信モジュール 外付け マルチプロトコル対応'),
    ('RISC-V デュアルコア マイコン 16bit メモリ512KB REACH対応 Embedded-3274B'),
    ('無線 CAN 通信モジュール 10Gbps マルチプロトコル対応 RoHS対応 IoT-4054R'),
    ('ポータブル ロジアナ デジタル計測器 帯域200MHz 2GS/s ノイズ耐性強化 Advanced-9630B'),
    ('無線 WiFi 通信モジュール 外付け メッシュネットワーク対応'),
    ('堅牢 UART インターフェース Ver2.0 ESD保護機能付 FCC認証取得'),
    ('高速 USB インターフェース Gen4 オートネゴシエーション VCCI Class B Industrial-7059C'),
    ('産業用 RS485 通信モジュール 通信速度100Mbps マルチプロトコル対応 長寿命設計 Embedded-4060R'),
    ('ハンディ オシロスコープ デジタル計測器 チャンネル2CH サンプリング1GS/s'),
    ('環境 I2C接続 センサーモジュール 小型3mm角 サンプリング10kHz'),
    ('温湿度 アナログ出力 センサーモジュール 5V動作 分解能16bit ノイズ耐性強化'),
    ('RISC-V 高性能 マイコン 200MHz メモリ256KB ノイズ耐性強化 Advanced-6395S'),
    ('セキュア Ethernet 通信モジュール アンテナ内蔵 メッシュネットワーク対応 高信頼性 Embedded-6396A'),
    ('有線 WiFi 通信モジュール アンテナ内蔵 メッシュネットワーク対応 Industrial-9938C'),
    ('産業用 CAN 通信モジュール 1Gbps マルチプロトコル対応 REACH対応 ノイズ耐性強化 Smart-7476A'),
    ('リニア 絶縁型 電源IC DIP 効率95% Advanced-9412C'),
    ('加速度 SPI接続 センサーモジュール 3.3V動作 低消費電力1mA以下 VCCI Class B Pro-7924C'),
    ('LDO 降圧型 電源IC パッケージSOP 効率95% VCCI Class B'),
    ('AC-DC 絶縁型 電源IC DIP 効率98%'),
    ('温湿度 SPI接続 センサーモジュール 小型3mm角 サンプリング10kHz Industrial-5917S'),
    ('AVR 省電力 マイコン 16bit メモリ1MB'),
    ('環境 デジタル出力 センサーモジュール 1.8V動作 サンプリング10kHz VCCI Class B Advanced-7026C'),
    ('リニア 絶縁型 電源IC DIP スタンバイ機能付 REACH対応 Smart-5679A'),
    ('ノイズ対策 UART インターフェース Gen3 ホットプラグ対応 FCC認証取得'),
    ('LDO 降圧型 電源IC DIP スタンバイ機能付'),
    ('リニア 絶縁型 電源IC QFN 保護回路内蔵 ノイズ耐性強化'),
    ('加速度 I2C接続 センサーモジュール 超小型2mm角 サンプリング10kHz Embedded-6456A'),
    ('AC-DC 昇圧型 電源IC パッケージSOP 入力範囲4-60V 省電力設計'),
    ('リニア 昇圧型 電源IC 出力5A 効率98% IoT-5517B'),
    ('IoT RS485 通信モジュール アンテナ内蔵 暗号化機能付 Pro-4201B'),
    ('ポータブル スペアナ デジタル計測器 8CH 2M'),
    ('AVR 組込み向け マイコン クロック周波数100MHz GPIO 64pin VCCI Class B Advanced-5793R'),
    ('高速 UART インターフェース Gen5 オートネゴシエーション Industrial-1507A'),
    ('スイッチング 同期整流 電源IC QFN 保護回路内蔵 ノイズ耐性強化'),
    ('有線 CAN 通信モジュール アンテナ内蔵 メッシュネットワーク対応 CE認証取得 高信頼性 Embedded-3116C'),
    ('近接 I2C接続 センサーモジュール 小型3mm角 分解能16bit'),
    ('産業用 組込み向け マイコン 400MHz メモリ512KB EMC対策済 Pro-8138C'),
    ('AC-DC 同期整流 電源IC QFN スタンバイ機能付 VCCI Class B'),
    ('AC-DC 同期整流 電源IC QFN 保護回路内蔵 CE認証取得 Pro-3957A'),
    ('ハンディ ロジアナ デジタル計測器 帯域200MHz 2M VCCI Class B 省電力設計 IoT-6131S'),
    ('IoT Ethernet 通信モジュール アンテナ内蔵 マルチプロトコル対応 EMC対策済'),
    ('ベンチトップ マルチメータ デジタル計測器 帯域200MHz 4GS/s'),
    ('ポータブル パワーメータ デジタル計測器 500MHz サンプリング1GS/s CE認証取得 IoT-1505B'),
    ('堅牢 USB インターフェース Gen5 オートネゴシエーション EMC対策済 Smart-6033R'),
    ('堅牢 HDMI インターフェース Ver2.0 ESD保護機能付'),
    ('絶縁 PCIe インターフェース Ver2.0 ホットプラグ対応 REACH対応'),
    ('近接 アナログ出力 センサーモジュール 小型3mm角 低消費電力1mA以下 RoHS対応'),
    ('ノイズ対策 PCIe インターフェース Ver3.0 ESD保護機能付 VCCI Class B 長寿命設計'),
    ('LDO 昇圧型 電源IC パッケージSOP 効率95%'),
    ('産業用 Ethernet 通信モジュール 1Gbps セキュリティ機能搭載 VCCI Class B'),
    ('AC-DC 同期整流 電源IC 出力5A 効率98% REACH対応 IoT-4513C'),
    ('ポータブル ロジアナ デジタル計測器 4CH 2M'),
    ('産業用 高性能 マイコン 400MHz メモリ1MB Pro-9579R'),
    ('近接 I2C接続 センサーモジュール 3.3V動作 低消費電力1mA以下 RoHS対応'),
    ('スイッチング 降圧型 電源IC QFN スタンバイ機能付'),
    ('産業用 デュアルコア マイコン 400MHz メモリ256KB'),
    ('堅牢 USB インターフェース Gen3 サージ保護付'),
    ('環境 I2C接続 センサーモジュール 1.8V動作 分解能16bit VCCI Class B'),
    ('ノイズ対策 USB インターフェース Ver4.0 ESD保護機能付 FCC認証取得 Embedded-9543R'),
    ('ポータブル スペアナ デジタル計測器 4CH 4GS/s ノイズ耐性強化 Smart-5589A'),
    ('ベンチトップ ロジアナ デジタル計測器 帯域100MHz 4GS/s CE認証取得 Smart-2216S'),
    ('産業用 高性能 マイコン 400MHz GPIO 64pin Smart-5028A'),
    ('温湿度 SPI接続 センサーモジュール 小型3mm角 サンプリング10kHz Advanced-4315S'),
    ('LDO 同期整流 電源IC 出力3A 効率95% Smart-7399B'),
    ('AVR 省電力 マイコン 200MHz GPIO 64pin'),
    ('セキュア WiFi 通信モジュール 10Gbps 暗号化機能付 高信頼性'),
    ('ハンディ マルチメータ デジタル計測器 500MHz 4M 省電力設計'),
    ('車載用 高性能 マイコン 16bit メモリ1MB EMC対策済 Embedded-7359C'),
    ('スイッチング 絶縁型 電源IC パッケージSOP 保護回路内蔵'),
    ('RISC-V Cortex-M マイコン 64bit メモリ256KB IoT-9263R'),
    ('ノイズ対策 DisplayPort インターフェース Gen4 オートネゴシエーション'),
    ('堅牢 USB インターフェース Gen4 オートネゴシエーション Advanced-8080A'),
    ('環境 デジタル出力 センサーモジュール 5V動作 分解能16bit Pro-6592A'),
    ('AVR 高性能 マイコン クロック周波数100MHz GPIO 100pin REACH対応'),
    ('スイッチング 昇圧型 電源IC パッケージSOP 効率98% Embedded-7970C'),
    ('据置 スペアナ デジタル計測器 4CH 4M REACH対応'),
    ('IoT WiFi 通信モジュール 10Gbps 暗号化機能付'),
    ('スイッチング 昇降圧型 電源IC パッケージSOP 保護回路内蔵 Smart-4037R'),
    ('環境 デジタル出力 センサーモジュール 超小型2mm角 分解能16bit REACH対応'),
    ('ポータブル オシロスコープ デジタル計測器 チャンネル2CH 4GS/s Pro-8393S'),
    ('産業用 CAN 通信モジュール 1Gbps セキュリティ機能搭載 Industrial-3985S'),
    ('近接 アナログ出力 センサーモジュール 超小型2mm角 分解能16bit 高信頼性 Pro-5472C'),
    ('据置 スペアナ デジタル計測器 帯域100MHz サンプリング1GS/s Pro-8011B'),
    ('ARM 省電力 マイコン 400MHz メモリ512KB REACH対応'),
    ('ハンディ パワーメータ デジタル計測器 500MHz メモリ長1M UL認証取得 省電力設計 Pro-9703A'),
    ('産業用 DisplayPort インターフェース Gen3 ESD保護機能付 FCC認証取得'),
    ('堅牢 HDMI インターフェース Ver3.0 ESD保護機能付'),
    ('絶縁 HDMI インターフェース Gen4 サージ保護付 省電力設計 Smart-1954R'),
    ('ベンチトップ マルチメータ デジタル計測器 帯域100MHz 4GS/s UL認証取得 高信頼性'),
    ('据置 オシロスコープ デジタル計測器 4CH 2M'),
    ('据置 マルチメータ デジタル計測器 チャンネル2CH 4M Industrial-5749R'),
    ('有線 Bluetooth 通信モジュール 外付け セキュリティ機能搭載 EMC対策済'),
    ('堅牢 HDMI インターフェース Gen4 ホットプラグ対応'),
    ('産業用 RS485 通信モジュール 外付け セキュリティ機能搭載 Embedded-4908B'),
    ('加速度 SPI接続 センサーモジュール 3.3V動作 サンプリング10kHz VCCI Class B Advanced-9556B'),
    ('ポータブル ロジアナ デジタル計測器 500MHz 4M Smart-1724S'),
    ('スイッチング 昇圧型 電源IC パッケージSOP スタンバイ機能付 省電力設計'),
    ('セキュア Bluetooth 通信モジュール 1Gbps メッシュネットワーク対応 EMC対策済 Advanced-2150R'),
    ('ポータブル マルチメータ デジタル計測器 500MHz 2GS/s Smart-6013R'),
    ('堅牢 UART インターフェース Gen5 オートネゴシエーション Advanced-8803S'),
    ('高機能 マルチメータ デジタル計測器 帯域100MHz 4M Advanced-9939C'),
    ('堅牢 UART インターフェース Gen3 オートネゴシエーション Smart-2467S'),
    ('近接 高精度 センサーモジュール 超小型2mm角 サンプリング1kHz IoT-1948B'),
    ('RISC-V 省電力 マイコン クロック周波数100MHz GPIO 32pin Embedded-5913C'),
    ('加速度 デジタル出力 センサーモジュール 5V動作 低消費電力1mA以下 Industrial-5190A'),
    ('温湿度 I2C接続 センサーモジュール 3.3V動作 サンプリング10kHz'),
    ('AVR Cortex-M マイコン 400MHz GPIO 100pin'),
    ('有線 CAN 通信モジュール 1Gbps 暗号化機能付 Industrial-5505B'),
    ('環境 I2C接続 センサーモジュール 5V動作 サンプリング10kHz UL認証取得 長寿命設計 Smart-8614A'),
    ('ノイズ対策 USB インターフェース Gen5 サージ保護付 長寿命設計 Embedded-3081A'),
    ('ジャイロ SPI接続 センサーモジュール 3.3V動作 低消費電力1mA以下 Advanced-4092C'),
    ('有線 Bluetooth 通信モジュール 1Gbps セキュリティ機能搭載 CE認証取得 Smart-2535R'),
    ('有線 Ethernet 通信モジュール アンテナ内蔵 マルチプロトコル対応 IoT-4401S'),
    ('ノイズ対策 PCIe インターフェース Ver2.0 ESD保護機能付 Pro-2950C'),
    ('RISC-V Cortex-M マイコン 16bit メモリ512KB RoHS対応 Pro-9517S'),
    ('ハンディ オシロスコープ デジタル計測器 500MHz 4M Smart-8323A'),
    ('リニア 昇降圧型 電源IC QFN 効率95% ノイズ耐性強化 Advanced-5673S'),
    ('ノイズ対策 UART インターフェース Ver3.0 オートネゴシエーション UL認証取得 Industrial-1416B'),
    ('温湿度 高精度 センサーモジュール 小型3mm角 分解能16bit UL認証取得 Embedded-7530R'),
    ('ベンチトップ パワーメータ デジタル計測器 8CH 2M'),
    ('据置 スペアナ デジタル計測器 帯域100MHz サンプリング1GS/s Industrial-7669A'),
    ('AVR 高性能 マイコン 400MHz GPIO 64pin Industrial-9648C'),
    ('AVR Cortex-M マイコン 200MHz メモリ512KB REACH対応 長寿命設計 Pro-2901C'),
    ('高機能 オシロスコープ デジタル計測器 4CH サンプリング1GS/s RoHS対応 Industrial-3407C'),
    ('温湿度 デジタル出力 センサーモジュール 1.8V動作 サンプリング10kHz FCC認証取得 EMC対策済 Embedded-3223B'),
    ('スイッチング 同期整流 電源IC QFN 効率95% EMC対策済'),
    ('産業用 DisplayPort インターフェース Gen3 ESD保護機能付 省電力設計 Smart-2539R'),
    ('ノイズ対策 USB インターフェース Ver4.0 ホットプラグ対応 EMC対策済 Embedded-5245C'),
    ('ハンディ パワーメータ デジタル計測器 500MHz 4M IoT-5033R'),
    ('産業用 Cortex-M マイコン 200MHz メモリ512KB Advanced-7535B'),
    ('高速 USB インターフェース Gen5 オートネゴシエーション FCC認証取得 EMC対策済 Embedded-8751A'),
    ('無線 RS485 通信モジュール 外付け メッシュネットワーク対応 IoT-9249C'),
    ('産業用 Ethernet 通信モジュール 通信速度100Mbps マルチプロトコル対応 Pro-5370C'),
    ('絶縁 USB インターフェース Ver2.0 オートネゴシエーション'),
    ('DC-DC 降圧型 電源IC QFN 効率98% UL認証取得 長寿命設計 Advanced-7612R'),
    ('環境 I2C接続 センサーモジュール 5V動作 サンプリング10kHz Embedded-4164B'),
    ('IoT CAN 通信モジュール 通信速度100Mbps セキュリティ機能搭載 Pro-2604A'),
    ('DC-DC 同期整流 電源IC 出力1A スタンバイ機能付 Industrial-7746A'),
    ('高機能 スペアナ デジタル計測器 帯域200MHz メモリ長1M 長寿命設計 Advanced-5359S'),
    ('リニア 同期整流 電源IC 出力3A 保護回路内蔵 Pro-1480A'),
    ('LDO 絶縁型 電源IC DIP 効率95% Advanced-2115S'),
    ('セキュア WiFi 通信モジュール 外付け 暗号化機能付 REACH対応 高信頼性 Advanced-7294C'),
    ('AC-DC 降圧型 電源IC 出力3A 効率98% VCCI Class B'),
    ('LDO 昇圧型 電源IC 出力5A 効率95% Industrial-1141A'),
    ('リニア 昇降圧型 電源IC 出力3A スタンバイ機能付'),
    ('AVR Cortex-M マイコン 400MHz メモリ512KB 長寿命設計'),
    ('スイッチング 降圧型 電源IC 出力3A 効率98% IoT-5745C'),
    ('ポータブル オシロスコープ デジタル計測器 チャンネル2CH 2M UL認証取得 Smart-8873S'),
    ('ARM デュアルコア マイコン 400MHz GPIO 64pin FCC認証取得 Embedded-3888R'),
    ('環境 デジタル出力 センサーモジュール 3.3V動作 低消費電力1mA以下'),
    ('高機能 スペアナ デジタル計測器 帯域100MHz 2GS/s RoHS対応 省電力設計 Industrial-4613A'),
    ('AC-DC 降圧型 電源IC DIP 保護回路内蔵'),
    ('ベンチトップ オシロスコープ デジタル計測器 帯域100MHz メモリ長1M'),
    ('リニア 絶縁型 電源IC QFN 入力範囲4-60V REACH対応'),
    ('スイッチング 絶縁型 電源IC DIP 効率95%'),
    ('ジャイロ I2C接続 センサーモジュール 5V動作 サンプリング1kHz'),
    ('ノイズ対策 UART インターフェース Gen4 ESD保護機能付'),
    ('産業用 UART インターフェース Gen4 ESD保護機能付 FCC認証取得 IoT-7565C'),
    ('ベンチトップ オシロスコープ デジタル計測器 4CH 4GS/s REACH対応 ノイズ耐性強化 Smart-3599A'),
    ('ノイズ対策 PCIe インターフェース Gen3 ESD保護機能付 ノイズ耐性強化 Pro-2762R'),
    ('加速度 アナログ出力 センサーモジュール 5V動作 低消費電力1mA以下'),
    ('車載用 Cortex-M マイコン 400MHz メモリ256KB RoHS対応 Industrial-9549B'),
    ('無線 WiFi 通信モジュール 通信速度100Mbps マルチプロトコル対応'),
    ('環境 I2C接続 センサーモジュール 超小型2mm角 低消費電力1mA以下 FCC認証取得'),
    ('ハンディ スペアナ デジタル計測器 帯域100MHz 4M Pro-3868S'),
    ('産業用 高性能 マイコン 64bit メモリ256KB REACH対応'),
    ('高速 PCIe インターフェース Gen3 ホットプラグ対応 CE認証取得 Industrial-9284R'),
    ('環境 SPI接続 センサーモジュール 5V動作 分解能16bit RoHS対応 IoT-1476B'),
    ('ARM 省電力 マイコン 200MHz GPIO 64pin VCCI Class B'),
    ('ハンディ ロジアナ デジタル計測器 500MHz 2GS/s IoT-6305C'),
    ('近接 アナログ出力 センサーモジュール 5V動作 分解能16bit Pro-4476A'),
    ('高速 HDMI インターフェース Ver4.0 ESD保護機能付 高信頼性 Industrial-7282C'),
    ('環境 高精度 センサーモジュール 1.8V動作 低消費電力1mA以下 REACH対応 省電力設計 Smart-6174S'),
    ('RISC-V Cortex-M マイコン 200MHz メモリ512KB VCCI Class B'),
    ('産業用 CAN 通信モジュール 通信速度100Mbps セキュリティ機能搭載 VCCI Class B'),
    ('温湿度 I2C接続 センサーモジュール 超小型2mm角 分解能16bit RoHS対応 高信頼性'),
    ('温湿度 デジタル出力 センサーモジュール 超小型2mm角 分解能24bit'),
    ('ハンディ ロジアナ デジタル計測器 チャンネル2CH 2M'),
    ('セキュア RS485 通信モジュール 10Gbps セキュリティ機能搭載 IoT-9935C'),
    ('ベンチトップ ロジアナ デジタル計測器 500MHz メモリ長1M EMC対策済 IoT-8926B'),
    ('ノイズ対策 HDMI インターフェース Ver3.0 サージ保護付 IoT-7415B'),
    ('RISC-V 省電力 マイコン クロック周波数100MHz メモリ256KB CE認証取得'),
    ('有線 Ethernet 通信モジュール 10Gbps メッシュネットワーク対応 CE認証取得 Smart-5172A'),
    ('環境 デジタル出力 センサーモジュール 小型3mm角 分解能24bit Embedded-7363R'),
    ('ジャイロ デジタル出力 センサーモジュール 1.8V動作 低消費電力1mA以下 FCC認証取得'),
    ('AVR 組込み向け マイコン 64bit GPIO 64pin Industrial-1763C'),
    ('温湿度 SPI接続 センサーモジュール 5V動作 分解能24bit'),
    ('無線 Ethernet 通信モジュール 通信速度100Mbps メッシュネットワーク対応 IoT-4940C'),
    ('無線 Bluetooth 通信モジュール 10Gbps セキュリティ機能搭載 RoHS対応'),
    ('AC-DC 昇降圧型 電源IC パッケージSOP 入力範囲4-60V ノイズ耐性強化 Industrial-4167S'),
    ('絶縁 USB インターフェース Ver3.0 ホットプラグ対応 FCC認証取得 Advanced-9060R'),
    ('環境 高精度 センサーモジュール 5V動作 低消費電力1mA以下 RoHS対応 ノイズ耐性強化 Embedded-1154C'),
    ('ハンディ ロジアナ デジタル計測器 帯域200MHz サンプリング1GS/s Industrial-1698B'),
    ('加速度 高精度 センサーモジュール 5V動作 分解能24bit'),
    ('ARM 組込み向け マイコン 16bit GPIO 64pin Smart-4603A'),
    ('産業用 WiFi 通信モジュール 10Gbps メッシュネットワーク対応 Advanced-6661C'),
    ('高速 PCIe インターフェース Gen4 ESD保護機能付 Embedded-3190C'),
    ('高速 HDMI インターフェース Ver3.0 サージ保護付 IoT-2698C'),
    ('有線 RS485 通信モジュール アンテナ内蔵 メッシュネットワーク対応'),
    ('ポータブル スペアナ デジタル計測器 帯域200MHz 4M RoHS対応'),
    ('RISC-V Cortex-M マイコン クロック周波数100MHz メモリ1MB RoHS対応 EMC対策済 Industrial-3597A'),
    ('ベンチトップ マルチメータ デジタル計測器 500MHz 2GS/s Advanced-5920A'),
    ('ノイズ対策 UART インターフェース Gen4 オートネゴシエーション Advanced-2558B'),
    ('IoT Bluetooth 通信モジュール アンテナ内蔵 セキュリティ機能搭載 Smart-4918A'),
    ('IoT RS485 通信モジュール 10Gbps マルチプロトコル対応 CE認証取得'),
    ('ベンチトップ スペアナ デジタル計測器 帯域200MHz 2GS/s'),
    ('DC-DC 絶縁型 電源IC QFN 保護回路内蔵 REACH対応 Embedded-9517S'),
    ('産業用 組込み向け マイコン 400MHz メモリ256KB 省電力設計 Pro-5839R'),
    ('スイッチング 昇降圧型 電源IC 出力5A 入力範囲4-60V 長寿命設計'),
    ('スイッチング 昇圧型 電源IC QFN 入力範囲4-60V'),
    ('IoT WiFi 通信モジュール 外付け メッシュネットワーク対応 RoHS対応 高信頼性 IoT-8140B'),
    ('セキュア Bluetooth 通信モジュール 10Gbps マルチプロトコル対応 Pro-3698R'),
    ('AC-DC 同期整流 電源IC 出力3A 入力範囲4-60V Industrial-6593C'),
    ('有線 Ethernet 通信モジュール 10Gbps メッシュネットワーク対応 REACH対応 EMC対策済 Embedded-3063C'),
    ('LDO 昇降圧型 電源IC QFN 保護回路内蔵'),
    ('RISC-V 組込み向け マイコン 400MHz GPIO 100pin'),
    ('ARM デュアルコア マイコン 200MHz メモリ256KB ノイズ耐性強化'),
    ('ポータブル ロジアナ デジタル計測器 500MHz 2GS/s UL認証取得 Advanced-3850B'),
    ('DC-DC 同期整流 電源IC QFN 効率98% Embedded-9543S'),
    ('堅牢 PCIe インターフェース Ver4.0 ホットプラグ対応'),
    ('AC-DC 同期整流 電源IC DIP 効率95% VCCI Class B Industrial-1280R'),
    ('セキュア Bluetooth 通信モジュール 通信速度100Mbps マルチプロトコル対応 VCCI Class B 長寿命設計 Pro-2069C'),
    ('近接 I2C接続 センサーモジュール 1.8V動作 分解能16bit FCC認証取得'),
    ('LDO 同期整流 電源IC 出力3A 保護回路内蔵'),
    ('車載用 Cortex-M マイコン 32bit メモリ1MB 高信頼性'),
    ('ポータブル パワーメータ デジタル計測器 帯域100MHz 2GS/s'),
    ('RISC-V 組込み向け マイコン 16bit GPIO 32pin ノイズ耐性強化 Advanced-2048B'),
    ('リニア 昇降圧型 電源IC 出力3A スタンバイ機能付 Embedded-5521C'),
    ('ノイズ対策 PCIe インターフェース Gen3 ESD保護機能付 FCC認証取得'),
    ('産業用 高性能 マイコン クロック周波数100MHz メモリ512KB VCCI Class B'),
    ('高機能 ロジアナ デジタル計測器 4CH サンプリング1GS/s Embedded-7451S'),
    ('ARM 省電力 マイコン 400MHz メモリ256KB 長寿命設計'),
    ('産業用 WiFi 通信モジュール 通信速度100Mbps セキュリティ機能搭載'),
    ('AC-DC 同期整流 電源IC QFN 入力範囲4-60V Pro-2060C'),
    ('ノイズ対策 UART インターフェース Gen4 サージ保護付 ノイズ耐性強化 Industrial-1383A'),
    ('LDO 昇降圧型 電源IC 出力5A 効率98%'),
    ('DC-DC 昇圧型 電源IC 出力1A 効率98%'),
    ('ジャイロ I2C接続 センサーモジュール 小型3mm角 分解能16bit ノイズ耐性強化 Industrial-1102C'),
    ('高速 HDMI インターフェース Gen4 サージ保護付 UL認証取得 ノイズ耐性強化 Advanced-4060C'),
    ('RISC-V デュアルコア マイコン 16bit GPIO 32pin 省電力設計 IoT-1902C'),
    ('産業用 高性能 マイコン クロック周波数100MHz GPIO 64pin VCCI Class B ノイズ耐性強化 Embedded-8902S'),
    ('環境 高精度 センサーモジュール 小型3mm角 分解能16bit Advanced-8334A'),
    ('産業用 Bluetooth 通信モジュール 1Gbps マルチプロトコル対応 FCC認証取得'),
    ('温湿度 デジタル出力 センサーモジュール 小型3mm角 分解能16bit'),
    ('DC-DC 昇降圧型 電源IC DIP 保護回路内蔵'),
    ('堅牢 PCIe インターフェース Ver4.0 サージ保護付 REACH対応'),
    ('産業用 高性能 マイコン 200MHz GPIO 32pin'),
    ('ポータブル スペアナ デジタル計測器 帯域200MHz 2GS/s 長寿命設計'),
    ('スイッチング 昇降圧型 電源IC QFN 効率95% UL認証取得 IoT-1235B'),
    ('無線 CAN 通信モジュール 1Gbps メッシュネットワーク対応 Smart-2000C'),
    ('ハンディ マルチメータ デジタル計測器 500MHz 2M Embedded-3211S'),
    ('堅牢 USB インターフェース Gen3 ESD保護機能付 省電力設計'),
    ('DC-DC 昇降圧型 電源IC 出力5A 効率98% Industrial-2479B'),
    ('AVR 高性能 マイコン 64bit メモリ1MB 長寿命設計'),
    ('RISC-V Cortex-M マイコン 64bit GPIO 32pin 高信頼性'),
    ('堅牢 PCIe インターフェース Ver3.0 サージ保護付 UL認証取得 Advanced-5346B'),
    ('セキュア Ethernet 通信モジュール 通信速度100Mbps 暗号化機能付'),
    ('産業用 WiFi 通信モジュール 外付け 暗号化機能付'),
    ('近接 SPI接続 センサーモジュール 3.3V動作 分解能24bit CE認証取得 IoT-2539A'),
    ('絶縁 PCIe インターフェース Ver4.0 ホットプラグ対応'),
    ('加速度 デジタル出力 センサーモジュール 小型3mm角 低消費電力1mA以下 IoT-4451B'),
    ('据置 マルチメータ デジタル計測器 500MHz 4GS/s EMC対策済 Smart-6096S'),
    ('高機能 パワーメータ デジタル計測器 帯域200MHz 4M REACH対応 ノイズ耐性強化'),
    ('近接 I2C接続 センサーモジュール 5V動作 サンプリング10kHz CE認証取得 ノイズ耐性強化'),
    ('スイッチング 昇圧型 電源IC 出力5A スタンバイ機能付 VCCI Class B IoT-6934C'),
    ('ARM 省電力 マイコン 16bit GPIO 32pin Pro-1469C'),
    ('高機能 ロジアナ デジタル計測器 4CH サンプリング1GS/s CE認証取得 Embedded-8913A'),
    ('産業用 組込み向け マイコン 400MHz メモリ1MB CE認証取得 ノイズ耐性強化'),
    ('高機能 オシロスコープ デジタル計測器 チャンネル2CH 4GS/s REACH対応 EMC対策済'),
    ('セキュア Bluetooth 通信モジュール 10Gbps マルチプロトコル対応 Pro-1086R'),
    ('産業用 組込み向け マイコン 16bit メモリ512KB UL認証取得'),
    ('産業用 高性能 マイコン 400MHz メモリ1MB RoHS対応 Advanced-9626C'),
    ('RISC-V 組込み向け マイコン 16bit GPIO 64pin Advanced-2270B'),
    ('据置 パワーメータ デジタル計測器 帯域200MHz 4GS/s'),
    ('LDO 同期整流 電源IC パッケージSOP 保護回路内蔵 CE認証取得 高信頼性 Smart-7068A'),
    ('高速 DisplayPort インターフェース Ver4.0 サージ保護付 FCC認証取得'),
    ('リニア 昇圧型 電源IC パッケージSOP 保護回路内蔵 UL認証取得 Industrial-8459S'),
    ('据置 オシロスコープ デジタル計測器 帯域100MHz 4M'),
    ('AVR 高性能 マイコン 32bit メモリ256KB CE認証取得'),
    ('無線 RS485 通信モジュール アンテナ内蔵 マルチプロトコル対応'),
    ('IoT Bluetooth 通信モジュール アンテナ内蔵 暗号化機能付 Embedded-7059A'),
    ('LDO 降圧型 電源IC QFN 効率98%'),
    ('スイッチング 昇圧型 電源IC 出力5A 効率95% Smart-2446A'),
    ('産業用 UART インターフェース Gen5 オートネゴシエーション Pro-6318C'),
    ('AVR 省電力 マイコン クロック周波数100MHz メモリ512KB Embedded-9147R'),
    ('ノイズ対策 USB インターフェース Gen4 ホットプラグ対応 Advanced-3925B'),
    ('環境 高精度 センサーモジュール 1.8V動作 分解能16bit CE認証取得 高信頼性 Industrial-1810C'),
    ('据置 ロジアナ デジタル計測器 4CH 4GS/s FCC認証取得 IoT-6513A'),
    ('LDO 同期整流 電源IC パッケージSOP 入力範囲4-60V REACH対応 Industrial-1183S'),
    ('据置 スペアナ デジタル計測器 4CH サンプリング1GS/s VCCI Class B Advanced-4935B'),
    ('IoT Bluetooth 通信モジュール 外付け メッシュネットワーク対応'),
    ('堅牢 DisplayPort インターフェース Gen4 オートネゴシエーション'),
    ('温湿度 デジタル出力 センサーモジュール 小型3mm角 分解能24bit Industrial-4632R'),
    ('堅牢 USB インターフェース Ver4.0 オートネゴシエーション'),
    ('AVR 高性能 マイコン 32bit GPIO 32pin UL認証取得'),
    ('堅牢 HDMI インターフェース Gen3 オートネゴシエーション IoT-1966C'),
    ('絶縁 UART インターフェース Ver3.0 オートネゴシエーション'),
    ('セキュア Ethernet 通信モジュール 10Gbps セキュリティ機能搭載'),
    ('リニア 昇圧型 電源IC 出力5A 入力範囲4-60V Pro-1464A'),
    ('高機能 オシロスコープ デジタル計測器 8CH 4M Embedded-2096R'),
    ('AC-DC 昇降圧型 電源IC QFN 入力範囲4-60V'),
    ('IoT Ethernet 通信モジュール 通信速度100Mbps セキュリティ機能搭載 REACH対応 Industrial-5000C'),
    ('有線 RS485 通信モジュール 10Gbps メッシュネットワーク対応 UL認証取得 Smart-3353B'),
    ('セキュア Ethernet 通信モジュール 通信速度100Mbps セキュリティ機能搭載 UL認証取得 長寿命設計'),
    ('IoT RS485 通信モジュール 10Gbps セキュリティ機能搭載'),
    ('絶縁 PCIe インターフェース Gen4 オートネゴシエーション EMC対策済 Embedded-4100S'),
    ('環境 I2C接続 センサーモジュール 超小型2mm角 低消費電力1mA以下 VCCI Class B'),
    ('近接 SPI接続 センサーモジュール 1.8V動作 分解能24bit Advanced-8568A'),
    ('産業用 Cortex-M マイコン 16bit GPIO 64pin EMC対策済 Pro-4289B'),
    ('ベンチトップ スペアナ デジタル計測器 チャンネル2CH 4GS/s RoHS対応'),
    ('高速 UART インターフェース Ver4.0 ESD保護機能付 高信頼性 Advanced-8545R'),
    ('IoT Ethernet 通信モジュール 10Gbps 暗号化機能付 Industrial-1859B'),
    ('産業用 USB インターフェース Ver4.0 ESD保護機能付 Smart-2701A'),
    ('温湿度 アナログ出力 センサーモジュール 小型3mm角 分解能16bit IoT-5971S'),
    ('加速度 SPI接続 センサーモジュール 1.8V動作 サンプリング10kHz Embedded-5083R'),
    ('車載用 Cortex-M マイコン 32bit メモリ256KB UL認証取得'),
    ('環境 I2C接続 センサーモジュール 3.3V動作 サンプリング1kHz Pro-4087C'),
    ('DC-DC 同期整流 電源IC パッケージSOP 効率95% Embedded-6360R'),
    ('高速 USB インターフェース Ver2.0 ホットプラグ対応 Embedded-8509C'),
    ('車載用 高性能 マイコン クロック周波数100MHz GPIO 64pin VCCI Class B'),
    ('DC-DC 絶縁型 電源IC パッケージSOP 効率95% 長寿命設計 IoT-1000R'),
    ('堅牢 DisplayPort インターフェース Ver4.0 サージ保護付 Embedded-8860A'),
    ('ジャイロ 高精度 センサーモジュール 5V動作 サンプリング1kHz Advanced-2638R'),
    ('AC-DC 絶縁型 電源IC 出力5A 効率95% IoT-4300A'),
    ('据置 ロジアナ デジタル計測器 4CH 4M Industrial-4739S'),
    ('高速 USB インターフェース Gen3 ホットプラグ対応 FCC認証取得 EMC対策済 Embedded-9649B'),
    ('ポータブル パワーメータ デジタル計測器 帯域200MHz メモリ長1M Embedded-2711C'),
    ('環境 アナログ出力 センサーモジュール 1.8V動作 サンプリング1kHz Industrial-1262S'),
    ('AVR 組込み向け マイコン 16bit メモリ1MB'),
    ('IoT Bluetooth 通信モジュール 通信速度100Mbps セキュリティ機能搭載 Smart-8527C'),
    ('産業用 DisplayPort インターフェース Gen3 サージ保護付'),
    ('加速度 デジタル出力 センサーモジュール 5V動作 サンプリング10kHz'),
    ('ジャイロ I2C接続 センサーモジュール 5V動作 サンプリング10kHz 高信頼性'),
    ('産業用 高性能 マイコン 16bit メモリ1MB ノイズ耐性強化 Smart-5258C'),
    ('産業用 Cortex-M マイコン 64bit メモリ1MB UL認証取得 ノイズ耐性強化 IoT-7212S'),
    ('産業用 Ethernet 通信モジュール 通信速度100Mbps 暗号化機能付 Embedded-5978A'),
    ('産業用 デュアルコア マイコン 64bit メモリ1MB ノイズ耐性強化 Advanced-3343S'),
    ('ジャイロ アナログ出力 センサーモジュール 1.8V動作 サンプリング10kHz Embedded-8141A'),
    ('リニア 絶縁型 電源IC 出力1A 保護回路内蔵'),
    ('AC-DC 昇降圧型 電源IC QFN 効率95%'),
    ('リニア 絶縁型 電源IC 出力3A 入力範囲4-60V Embedded-7743C'),
    ('絶縁 PCIe インターフェース Ver3.0 オートネゴシエーション ノイズ耐性強化 Advanced-1834S'),
    ('産業用 CAN 通信モジュール アンテナ内蔵 暗号化機能付 FCC認証取得 Smart-2958S'),
    ('RISC-V Cortex-M マイコン クロック周波数100MHz メモリ512KB Advanced-2250C'),
    ('車載用 デュアルコア マイコン 64bit GPIO 32pin Advanced-5464S'),
    ('ジャイロ I2C接続 センサーモジュール 5V動作 低消費電力1mA以下 FCC認証取得 Smart-6876C'),
    ('産業用 省電力 マイコン クロック周波数100MHz メモリ1MB IoT-8885S'),
    ('ノイズ対策 PCIe インターフェース Ver4.0 サージ保護付 Industrial-9962R'),
    ('産業用 Ethernet 通信モジュール 外付け マルチプロトコル対応'),
    ('産業用 DisplayPort インターフェース Gen4 ESD保護機能付 EMC対策済 Smart-6438S'),
    ('ポータブル スペアナ デジタル計測器 4CH 2GS/s 高信頼性'),
    ('有線 RS485 通信モジュール 通信速度100Mbps セキュリティ機能搭載'),
    ('車載用 高性能 マイコン 64bit メモリ256KB 長寿命設計 IoT-4666C'),
    ('ベンチトップ オシロスコープ デジタル計測器 チャンネル2CH 2M Smart-8364S'),
    ('温湿度 デジタル出力 センサーモジュール 超小型2mm角 分解能16bit EMC対策済 Pro-9779S'),
    ('AVR 省電力 マイコン 32bit GPIO 32pin Advanced-8353B'),
    ('ノイズ対策 USB インターフェース Ver2.0 ホットプラグ対応 RoHS対応'),
    ('近接 高精度 センサーモジュール 小型3mm角 分解能24bit FCC認証取得'),
    ('温湿度 SPI接続 センサーモジュール 超小型2mm角 サンプリング10kHz'),
    ('ノイズ対策 DisplayPort インターフェース Ver2.0 サージ保護付 Industrial-2642S'),
    ('ポータブル マルチメータ デジタル計測器 帯域200MHz 4GS/s 省電力設計'),
    ('加速度 I2C接続 センサーモジュール 超小型2mm角 サンプリング1kHz Embedded-8070C'),
    ('RISC-V 高性能 マイコン クロック周波数100MHz メモリ1MB'),
    ('ポータブル ロジアナ デジタル計測器 500MHz 2M FCC認証取得 EMC対策済 Smart-4947R'),
    ('ハンディ マルチメータ デジタル計測器 500MHz 2M REACH対応'),
    ('産業用 WiFi 通信モジュール 通信速度100Mbps 暗号化機能付 UL認証取得 Industrial-7541A'),
    ('産業用 高性能 マイコン クロック周波数100MHz GPIO 100pin EMC対策済 Pro-5196A'),
    ('高機能 オシロスコープ デジタル計測器 帯域200MHz メモリ長1M IoT-2792A'),
    ('堅牢 USB インターフェース Gen3 ESD保護機能付'),
    ('環境 デジタル出力 センサーモジュール 1.8V動作 分解能16bit CE認証取得 Embedded-2681A'),
    ('ベンチトップ マルチメータ デジタル計測器 4CH サンプリング1GS/s Advanced-3388A'),
    ('車載用 組込み向け マイコン 32bit GPIO 100pin Industrial-7234R'),
    ('無線 Bluetooth 通信モジュール 1Gbps 暗号化機能付 IoT-4770A'),
    ('リニア 絶縁型 電源IC QFN 保護回路内蔵 長寿命設計'),
    ('産業用 Cortex-M マイコン 400MHz メモリ256KB IoT-7968S'),
    ('無線 WiFi 通信モジュール 10Gbps マルチプロトコル対応 省電力設計'),
    ('据置 ロジアナ デジタル計測器 チャンネル2CH 2GS/s Pro-9470B'),
    ('据置 ロジアナ デジタル計測器 帯域100MHz サンプリング1GS/s REACH対応 高信頼性'),
    ('ARM 高性能 マイコン 200MHz メモリ1MB 省電力設計'),
    ('AVR 高性能 マイコン 32bit GPIO 32pin FCC認証取得 Industrial-4940B'),
    ('温湿度 I2C接続 センサーモジュール 1.8V動作 低消費電力1mA以下 RoHS対応 Smart-8277S'),
    ('近接 デジタル出力 センサーモジュール 5V動作 低消費電力1mA以下 Pro-6089B'),
    ('ポータブル ロジアナ デジタル計測器 帯域100MHz サンプリング1GS/s IoT-8595B'),
    ('DC-DC 絶縁型 電源IC QFN 効率95% CE認証取得'),
    ('ポータブル スペアナ デジタル計測器 チャンネル2CH 2GS/s Embedded-7076B'),
    ('ベンチトップ オシロスコープ デジタル計測器 帯域200MHz 4M 省電力設計 Industrial-4813S'),
    ('車載用 組込み向け マイコン クロック周波数100MHz GPIO 64pin 高信頼性'),
    ('LDO 同期整流 電源IC DIP スタンバイ機能付 REACH対応 長寿命設計'),
    ('車載用 高性能 マイコン 16bit メモリ1MB Smart-4593B'),
    ('産業用 デュアルコア マイコン 16bit メモリ1MB CE認証取得 長寿命設計'),
    ('LDO 降圧型 電源IC 出力5A スタンバイ機能付 RoHS対応 Industrial-9340R'),
    ('ベンチトップ マルチメータ デジタル計測器 8CH 2M IoT-9197C'),
    ('温湿度 高精度 センサーモジュール 3.3V動作 分解能16bit VCCI Class B 省電力設計 Industrial-5861R'),
    ('絶縁 DisplayPort インターフェース Ver3.0 ESD保護機能付'),
    ('LDO 絶縁型 電源IC 出力1A 入力範囲4-60V Pro-3096B'),
    ('高速 UART インターフェース Gen5 サージ保護付 EMC対策済 Pro-1034R'),
    ('ジャイロ アナログ出力 センサーモジュール 超小型2mm角 サンプリング1kHz Industrial-7982R'),
    ('ノイズ対策 UART インターフェース Ver3.0 ホットプラグ対応 CE認証取得'),
    ('LDO 絶縁型 電源IC 出力3A 効率95% Industrial-2313R'),
    ('ARM デュアルコア マイコン 16bit メモリ512KB Embedded-2592C'),
    ('高速 PCIe インターフェース Ver3.0 サージ保護付 高信頼性'),
    ('RISC-V 組込み向け マイコン 400MHz メモリ1MB'),
    ('産業用 省電力 マイコン 400MHz メモリ1MB VCCI Class B'),
    ('ポータブル パワーメータ デジタル計測器 チャンネル2CH 4M VCCI Class B 省電力設計 Smart-8298R'),
    ('RISC-V デュアルコア マイコン 16bit GPIO 100pin REACH対応 Pro-3167B'),
    ('IoT Bluetooth 通信モジュール 10Gbps マルチプロトコル対応 FCC認証取得 Advanced-5154S'),
    ('環境 デジタル出力 センサーモジュール 超小型2mm角 分解能16bit Embedded-4927B'),
    ('ARM 省電力 マイコン 64bit GPIO 32pin Industrial-6292B'),
    ('ノイズ対策 USB インターフェース Gen4 オートネゴシエーション'),
    ('車載用 省電力 マイコン 400MHz メモリ1MB Industrial-1849A'),
    ('車載用 高性能 マイコン クロック周波数100MHz GPIO 64pin CE認証取得 Pro-2565A'),
    ('高速 DisplayPort インターフェース Ver3.0 ホットプラグ対応 Smart-4357C'),
    ('ポータブル パワーメータ デジタル計測器 帯域200MHz 2M Advanced-3858R'),
    ('IoT WiFi 通信モジュール 10Gbps 暗号化機能付 Embedded-6534A'),
    ('有線 CAN 通信モジュール 外付け 暗号化機能付 IoT-5983R'),
    ('産業用 DisplayPort インターフェース Gen5 ESD保護機能付'),
    ('LDO 昇圧型 電源IC QFN スタンバイ機能付 CE認証取得'),
    ('AVR Cortex-M マイコン 400MHz GPIO 100pin Pro-1037C'),
    ('ベンチトップ ロジアナ デジタル計測器 帯域100MHz メモリ長1M'),
    ('加速度 高精度 センサーモジュール 小型3mm角 分解能24bit RoHS対応'),
    ('高機能 オシロスコープ デジタル計測器 4CH メモリ長1M 高信頼性 IoT-6036A'),
    ('絶縁 UART インターフェース Gen5 オートネゴシエーション FCC認証取得 Embedded-9217C'),
    ('加速度 アナログ出力 センサーモジュール 5V動作 分解能24bit Advanced-7777A'),
    ('産業用 PCIe インターフェース Ver4.0 オートネゴシエーション Pro-8560S'),
    ('ハンディ ロジアナ デジタル計測器 500MHz サンプリング1GS/s Embedded-1320R'),
    ('絶縁 DisplayPort インターフェース Gen4 ESD保護機能付 Industrial-1842R'),
    ('車載用 Cortex-M マイコン 400MHz GPIO 100pin'),
    ('セキュア Ethernet 通信モジュール 外付け セキュリティ機能搭載 Embedded-8292B'),
    ('堅牢 UART インターフェース Ver4.0 オートネゴシエーション VCCI Class B'),
    ('近接 SPI接続 センサーモジュール 超小型2mm角 サンプリング1kHz Smart-4275S'),
    ('温湿度 アナログ出力 センサーモジュール 3.3V動作 サンプリング1kHz Advanced-5458S'),
    ('ベンチトップ スペアナ デジタル計測器 帯域200MHz 4M RoHS対応 EMC対策済'),
    ('IoT WiFi 通信モジュール アンテナ内蔵 メッシュネットワーク対応'),
    ('AVR 高性能 マイコン 32bit メモリ256KB Pro-1151B'),
    ('高速 USB インターフェース Gen4 オートネゴシエーション'),
    ('据置 スペアナ デジタル計測器 8CH 4M EMC対策済 IoT-1948C'),
    ('温湿度 デジタル出力 センサーモジュール 5V動作 低消費電力1mA以下'),
    ('ハンディ スペアナ デジタル計測器 帯域100MHz 2M VCCI Class B Advanced-8186C'),
    ('高機能 オシロスコープ デジタル計測器 4CH 4GS/s CE認証取得'),
    ('AC-DC 絶縁型 電源IC DIP 効率95% CE認証取得'),
    ('堅牢 UART インターフェース Gen5 オートネゴシエーション IoT-9638A'),
    ('据置 パワーメータ デジタル計測器 帯域200MHz 2GS/s Embedded-9423A'),
    ('ハンディ パワーメータ デジタル計測器 4CH 4GS/s 長寿命設計 Advanced-4587B'),
    ('スイッチング 昇圧型 電源IC パッケージSOP スタンバイ機能付 REACH対応 省電力設計'),
    ('産業用 デュアルコア マイコン 16bit GPIO 100pin REACH対応 IoT-8951B'),
    ('据置 マルチメータ デジタル計測器 500MHz メモリ長1M CE認証取得 Industrial-5080S'),
    ('堅牢 HDMI インターフェース Ver4.0 ホットプラグ対応 省電力設計 Pro-5345R'),
    ('ノイズ対策 USB インターフェース Gen4 ESD保護機能付 VCCI Class B IoT-6783S'),
    ('AC-DC 昇降圧型 電源IC 出力1A スタンバイ機能付 Smart-8642A'),
    ('加速度 SPI接続 センサーモジュール 1.8V動作 分解能16bit RoHS対応 Pro-7976S'),
    ('IoT WiFi 通信モジュール アンテナ内蔵 メッシュネットワーク対応 FCC認証取得 Embedded-3337A'),
    ('セキュア Ethernet 通信モジュール 通信速度100Mbps 暗号化機能付 UL認証取得 ノイズ耐性強化 Advanced-3620C'),
    ('ベンチトップ パワーメータ デジタル計測器 帯域100MHz 4GS/s VCCI Class B'),
    ('産業用 組込み向け マイコン クロック周波数100MHz GPIO 64pin CE認証取得'),
    ('AC-DC 降圧型 電源IC 出力1A 入力範囲4-60V Pro-2661C'),
    ('AVR Cortex-M マイコン 400MHz GPIO 32pin'),
    ('IoT Ethernet 通信モジュール 10Gbps 暗号化機能付'),
    ('産業用 PCIe インターフェース Gen4 ESD保護機能付 UL認証取得 長寿命設計 Smart-7042R'),
    ('有線 WiFi 通信モジュール 1Gbps マルチプロトコル対応 CE認証取得 省電力設計 Pro-3403R'),
    ('リニア 降圧型 電源IC 出力5A 効率95% Industrial-4533B'),
    ('ハンディ オシロスコープ デジタル計測器 500MHz 2GS/s'),
    ('絶縁 HDMI インターフェース Gen4 ESD保護機能付 UL認証取得'),
    ('ジャイロ デジタル出力 センサーモジュール 1.8V動作 分解能24bit'),
    ('温湿度 高精度 センサーモジュール 5V動作 サンプリング1kHz Industrial-3895B'),
    ('AVR 省電力 マイコン クロック周波数100MHz メモリ1MB RoHS対応 IoT-8157S'),
    ('AVR 省電力 マイコン クロック周波数100MHz メモリ256KB UL認証取得 Advanced-3889C'),
    ('スイッチング 降圧型 電源IC 出力3A 効率95%'),
    ('産業用 PCIe インターフェース Ver3.0 ホットプラグ対応'),
    ('加速度 SPI接続 センサーモジュール 小型3mm角 サンプリング1kHz'),
    ('有線 WiFi 通信モジュール 外付け 暗号化機能付 REACH対応 高信頼性 Smart-5730B'),
    ('ポータブル マルチメータ デジタル計測器 500MHz メモリ長1M'),
    ('産業用 RS485 通信モジュール 1Gbps セキュリティ機能搭載'),
    ('近接 デジタル出力 センサーモジュール 3.3V動作 サンプリング1kHz UL認証取得'),
    ('ポータブル オシロスコープ デジタル計測器 4CH 4M'),
    ('DC-DC 降圧型 電源IC 出力5A 入力範囲4-60V UL認証取得 Pro-3020C'),
    ('高機能 スペアナ デジタル計測器 帯域200MHz 2M REACH対応'),
    ('IoT CAN 通信モジュール アンテナ内蔵 暗号化機能付 Smart-9321S'),
    ('堅牢 UART インターフェース Gen5 オートネゴシエーション Industrial-3810R'),
    ('ノイズ対策 HDMI インターフェース Gen3 サージ保護付 Embedded-2445S'),
    ('環境 アナログ出力 センサーモジュール 小型3mm角 分解能24bit'),
    ('高機能 オシロスコープ デジタル計測器 8CH メモリ長1M ノイズ耐性強化 Industrial-2171S'),
    ('ポータブル パワーメータ デジタル計測器 帯域100MHz 2GS/s EMC対策済 Smart-3424B'),
    ('産業用 デュアルコア マイコン クロック周波数100MHz GPIO 32pin Advanced-1989C'),
    ('LDO 絶縁型 電源IC QFN 保護回路内蔵 UL認証取得'),
    ('IoT Ethernet 通信モジュール 1Gbps マルチプロトコル対応 VCCI Class B 高信頼性 Pro-1364C'),
    ('RISC-V 高性能 マイコン 32bit メモリ1MB Embedded-5335B'),
    ('有線 Bluetooth 通信モジュール 外付け 暗号化機能付 Smart-8472C'),
    ('RISC-V 高性能 マイコン クロック周波数100MHz GPIO 64pin RoHS対応 IoT-9848A'),
    ('有線 CAN 通信モジュール 1Gbps メッシュネットワーク対応 IoT-6534S'),
    ('産業用 PCIe インターフェース Gen4 ESD保護機能付 FCC認証取得 Embedded-3511C'),
    ('高機能 マルチメータ デジタル計測器 4CH 4GS/s'),
    ('DC-DC 同期整流 電源IC 出力5A 入力範囲4-60V RoHS対応'),
    ('ジャイロ SPI接続 センサーモジュール 5V動作 低消費電力1mA以下 長寿命設計 Industrial-6224A'),
    ('加速度 高精度 センサーモジュール 小型3mm角 サンプリング1kHz FCC認証取得 省電力設計'),
    ('DC-DC 同期整流 電源IC QFN 効率98% 省電力設計 IoT-1184C'),
    ('ベンチトップ パワーメータ デジタル計測器 帯域200MHz 2GS/s'),
    ('スイッチング 昇降圧型 電源IC パッケージSOP 入力範囲4-60V IoT-2110R'),
    ('車載用 省電力 マイコン 32bit メモリ1MB 長寿命設計 Advanced-7065B'),
    ('有線 WiFi 通信モジュール 1Gbps 暗号化機能付 IoT-5513S'),
    ('有線 RS485 通信モジュール 通信速度100Mbps メッシュネットワーク対応'),
    ('温湿度 デジタル出力 センサーモジュール 小型3mm角 分解能24bit Advanced-2767A'),
    ('高速 UART インターフェース Gen3 サージ保護付 VCCI Class B'),
    ('ノイズ対策 PCIe インターフェース Gen4 オートネゴシエーション Industrial-1676S'),
    ('ハンディ スペアナ デジタル計測器 帯域100MHz 4GS/s'),
    ('ARM 省電力 マイコン 64bit メモリ1MB Industrial-8512R'),
    ('温湿度 I2C接続 センサーモジュール 超小型2mm角 サンプリング1kHz CE認証取得'),
    ('加速度 I2C接続 センサーモジュール 1.8V動作 分解能24bit RoHS対応 Smart-4714C'),
    ('加速度 SPI接続 センサーモジュール 5V動作 サンプリング1kHz RoHS対応'),
    ('産業用 組込み向け マイコン 16bit メモリ1MB 長寿命設計 Industrial-8904S'),
    ('LDO 絶縁型 電源IC 出力3A 効率98% IoT-3030R'),
    ('ジャイロ アナログ出力 センサーモジュール 超小型2mm角 分解能16bit UL認証取得 Pro-5889A'),
    ('無線 WiFi 通信モジュール 通信速度100Mbps メッシュネットワーク対応'),
    ('ベンチトップ パワーメータ デジタル計測器 4CH 2GS/s Embedded-6845B'),
    ('環境 高精度 センサーモジュール 1.8V動作 サンプリング1kHz Embedded-7354B'),
    ('据置 オシロスコープ デジタル計測器 8CH 4GS/s'),
    ('ノイズ対策 UART インターフェース Ver3.0 ホットプラグ対応 Advanced-4824B'),
    ('加速度 デジタル出力 センサーモジュール 小型3mm角 サンプリング10kHz'),
    ('有線 WiFi 通信モジュール 10Gbps メッシュネットワーク対応 Advanced-6294B'),
    ('加速度 I2C接続 センサーモジュール 5V動作 分解能16bit 高信頼性'),
    ('スイッチング 昇圧型 電源IC パッケージSOP スタンバイ機能付 Pro-3433C'),
    ('有線 RS485 通信モジュール 通信速度100Mbps メッシュネットワーク対応 Pro-9676S'),
    ('RISC-V Cortex-M マイコン 64bit GPIO 64pin Pro-2796S'),
    ('ARM デュアルコア マイコン 200MHz メモリ512KB REACH対応'),
    ('ハンディ パワーメータ デジタル計測器 8CH メモリ長1M 省電力設計'),
    ('LDO 降圧型 電源IC QFN 保護回路内蔵 ノイズ耐性強化 Advanced-2636R'),
    ('ノイズ対策 PCIe インターフェース Ver2.0 ホットプラグ対応 省電力設計 Pro-5527R'),
    ('産業用 Ethernet 通信モジュール アンテナ内蔵 マルチプロトコル対応 EMC対策済'),
    ('AC-DC 昇降圧型 電源IC 出力3A 効率98% REACH対応 Smart-8725S'),
    ('無線 Bluetooth 通信モジュール 外付け 暗号化機能付 Industrial-9838B'),
    ('ARM デュアルコア マイコン 32bit メモリ256KB Smart-9062A'),
    ('無線 CAN 通信モジュール 通信速度100Mbps 暗号化機能付 高信頼性 Industrial-5295A'),
    ('産業用 CAN 通信モジュール 10Gbps セキュリティ機能搭載 CE認証取得 Advanced-2136A'),
    ('近接 デジタル出力 センサーモジュール 3.3V動作 サンプリング1kHz'),
    ('ノイズ対策 DisplayPort インターフェース Gen5 サージ保護付 VCCI Class B Advanced-6543B'),
    ('IoT WiFi 通信モジュール アンテナ内蔵 メッシュネットワーク対応 FCC認証取得 長寿命設計'),
    ('絶縁 USB インターフェース Ver2.0 オートネゴシエーション Advanced-7191S'),
    ('据置 マルチメータ デジタル計測器 チャンネル2CH 4M'),
    ('据置 パワーメータ デジタル計測器 8CH メモリ長1M REACH対応'),
    ('スイッチング 降圧型 電源IC 出力1A 入力範囲4-60V VCCI Class B Smart-7609A'),
    ('産業用 デュアルコア マイコン クロック周波数100MHz メモリ512KB IoT-6406S'),
    ('産業用 高性能 マイコン クロック周波数100MHz メモリ1MB FCC認証取得'),
    ('ジャイロ 高精度 センサーモジュール 3.3V動作 サンプリング10kHz REACH対応 高信頼性'),
    ('ポータブル オシロスコープ デジタル計測器 8CH 4M 長寿命設計 Smart-8235R'),
    ('LDO 昇降圧型 電源IC 出力5A 効率98% Industrial-9846A'),
    ('スイッチング 絶縁型 電源IC 出力5A 効率95% Smart-7952A'),
    ('環境 アナログ出力 センサーモジュール 1.8V動作 サンプリング10kHz CE認証取得'),
    ('絶縁 PCIe インターフェース Gen5 サージ保護付 UL認証取得 Advanced-3122C'),
    ('温湿度 高精度 センサーモジュール 超小型2mm角 分解能24bit'),
    ('リニア 同期整流 電源IC 出力1A スタンバイ機能付'),
    ('温湿度 SPI接続 センサーモジュール 超小型2mm角 サンプリング1kHz UL認証取得 Advanced-1326S'),
    ('車載用 省電力 マイコン 400MHz GPIO 64pin'),
    ('ARM 組込み向け マイコン 64bit メモリ512KB'),
    ('リニア 絶縁型 電源IC DIP 保護回路内蔵 Pro-1084C'),
    ('ベンチトップ スペアナ デジタル計測器 500MHz 2M IoT-5673B'),
    ('近接 高精度 センサーモジュール 1.8V動作 低消費電力1mA以下 FCC認証取得'),
    ('AVR 高性能 マイコン クロック周波数100MHz GPIO 64pin Embedded-2131A'),
    ('ベンチトップ ロジアナ デジタル計測器 500MHz メモリ長1M'),
    ('有線 RS485 通信モジュール 通信速度100Mbps 暗号化機能付 VCCI Class B ノイズ耐性強化 Pro-3147B'),
    ('堅牢 HDMI インターフェース Ver3.0 ホットプラグ対応'),
    ('RISC-V Cortex-M マイコン 64bit メモリ256KB'),
    ('温湿度 デジタル出力 センサーモジュール 超小型2mm角 サンプリング10kHz'),
    ('ノイズ対策 UART インターフェース Ver4.0 ホットプラグ対応 UL認証取得 Industrial-2340S'),
    ('近接 デジタル出力 センサーモジュール 超小型2mm角 サンプリング1kHz UL認証取得'),
    ('ジャイロ アナログ出力 センサーモジュール 5V動作 低消費電力1mA以下'),
    ('DC-DC 昇圧型 電源IC 出力1A スタンバイ機能付 CE認証取得 IoT-7325S'),
    ('RISC-V 省電力 マイコン 400MHz メモリ1MB 高信頼性'),
    ('加速度 高精度 センサーモジュール 超小型2mm角 サンプリング1kHz'),
    ('高速 USB インターフェース Ver2.0 オートネゴシエーション IoT-4886A'),
    ('リニア 絶縁型 電源IC パッケージSOP 保護回路内蔵 Embedded-1906C'),
    ('ベンチトップ ロジアナ デジタル計測器 チャンネル2CH メモリ長1M IoT-5098S'),
    ('セキュア Bluetooth 通信モジュール 1Gbps セキュリティ機能搭載 VCCI Class B Smart-4946C'),
    ('ARM 高性能 マイコン 200MHz メモリ512KB IoT-1340B'),
    ('無線 CAN 通信モジュール 外付け セキュリティ機能搭載'),
    ('車載用 デュアルコア マイコン 32bit GPIO 32pin REACH対応'),
    ('ハンディ スペアナ デジタル計測器 4CH メモリ長1M Smart-8279S'),
    ('ARM デュアルコア マイコン 16bit GPIO 32pin RoHS対応 高信頼性'),
    ('LDO 同期整流 電源IC QFN 効率95%'),
    ('堅牢 HDMI インターフェース Gen5 サージ保護付 VCCI Class B Embedded-8430C'),
    ('ARM デュアルコア マイコン クロック周波数100MHz メモリ512KB 省電力設計'),
    ('据置 マルチメータ デジタル計測器 帯域200MHz メモリ長1M Industrial-4776C'),
    ('リニア 絶縁型 電源IC 出力5A 入力範囲4-60V 長寿命設計 IoT-7921A'),
    ('近接 デジタル出力 センサーモジュール 5V動作 サンプリング1kHz CE認証取得 高信頼性 IoT-6185A'),
    ('堅牢 DisplayPort インターフェース Ver2.0 ESD保護機能付 Embedded-5262S'),
    ('環境 高精度 センサーモジュール 超小型2mm角 低消費電力1mA以下 Advanced-8256R'),
    ('スイッチング 降圧型 電源IC パッケージSOP スタンバイ機能付 Advanced-7360R'),
    ('車載用 Cortex-M マイコン クロック周波数100MHz GPIO 64pin UL認証取得'),
    ('加速度 高精度 センサーモジュール 5V動作 低消費電力1mA以下 Smart-9561R'),
    ('高速 USB インターフェース Gen3 ESD保護機能付 VCCI Class B IoT-5666R'),
    ('近接 高精度 センサーモジュール 5V動作 分解能24bit Advanced-5894B'),
    ('LDO 絶縁型 電源IC 出力5A 保護回路内蔵'),
    ('絶縁 HDMI インターフェース Gen5 ESD保護機能付 IoT-4559C'),
    ('ポータブル パワーメータ デジタル計測器 500MHz 4M IoT-6763B'),
    ('加速度 アナログ出力 センサーモジュール 超小型2mm角 分解能24bit RoHS対応 IoT-8522A'),
    ('堅牢 HDMI インターフェース Ver4.0 サージ保護付 高信頼性 Industrial-4871S'),
    ('ベンチトップ パワーメータ デジタル計測器 帯域200MHz メモリ長1M Pro-1272R'),
    ('産業用 PCIe インターフェース Gen5 ESD保護機能付'),
    ('ARM 高性能 マイコン 200MHz メモリ512KB'),
    ('ベンチトップ オシロスコープ デジタル計測器 4CH メモリ長1M'),
    ('セキュア CAN 通信モジュール 10Gbps メッシュネットワーク対応'),
    ('ジャイロ アナログ出力 センサーモジュール 小型3mm角 低消費電力1mA以下 UL認証取得 長寿命設計 Advanced-5183S'),
    ('加速度 高精度 センサーモジュール 超小型2mm角 分解能16bit REACH対応 Pro-3680C'),
    ('リニア 同期整流 電源IC パッケージSOP 保護回路内蔵'),
    ('RISC-V 組込み向け マイコン 400MHz メモリ512KB'),
    ('ハンディ ロジアナ デジタル計測器 チャンネル2CH 2M IoT-7894A'),
    ('スイッチング 絶縁型 電源IC 出力3A スタンバイ機能付 Pro-9866C'),
    ('RISC-V デュアルコア マイコン 64bit メモリ256KB'),
    ('温湿度 デジタル出力 センサーモジュール 超小型2mm角 サンプリング10kHz Pro-5081S'),
    ('AC-DC 絶縁型 電源IC QFN スタンバイ機能付 Industrial-1555R'),
    ('環境 デジタル出力 センサーモジュール 3.3V動作 低消費電力1mA以下 IoT-8475C'),
    ('車載用 組込み向け マイコン 16bit メモリ1MB Smart-3582A'),
    ('産業用 RS485 通信モジュール アンテナ内蔵 マルチプロトコル対応 省電力設計 Pro-6485S'),
    ('LDO 降圧型 電源IC パッケージSOP 入力範囲4-60V 高信頼性 Pro-8509R'),
    ('据置 ロジアナ デジタル計測器 チャンネル2CH 4M'),
    ('産業用 Bluetooth 通信モジュール 通信速度100Mbps メッシュネットワーク対応 Smart-2222S'),
    ('LDO 絶縁型 電源IC DIP 保護回路内蔵 UL認証取得'),
    ('ハンディ オシロスコープ デジタル計測器 帯域100MHz 4M UL認証取得 高信頼性'),
    ('車載用 高性能 マイコン 200MHz メモリ1MB'),
    ('産業用 省電力 マイコン 16bit メモリ512KB UL認証取得'),
    ('温湿度 SPI接続 センサーモジュール 小型3mm角 低消費電力1mA以下'),
    ('絶縁 UART インターフェース Gen5 ホットプラグ対応 ノイズ耐性強化'),
    ('産業用 Ethernet 通信モジュール 通信速度100Mbps 暗号化機能付 Pro-8426C'),
    ('DC-DC 同期整流 電源IC 出力3A 効率95%'),
    ('AC-DC 昇降圧型 電源IC 出力1A 効率98%'),
    ('ハンディ パワーメータ デジタル計測器 帯域100MHz サンプリング1GS/s REACH対応 IoT-6475C'),
    ('ノイズ対策 HDMI インターフェース Gen4 ホットプラグ対応 Smart-8014S'),
    ('セキュア RS485 通信モジュール アンテナ内蔵 マルチプロトコル対応'),
    ('ハンディ スペアナ デジタル計測器 500MHz 4GS/s Industrial-1277S'),
    ('絶縁 PCIe インターフェース Ver2.0 ホットプラグ対応 省電力設計'),
    ('無線 RS485 通信モジュール 通信速度100Mbps セキュリティ機能搭載 長寿命設計 IoT-7112S'),
    ('近接 I2C接続 センサーモジュール 5V動作 低消費電力1mA以下 Smart-2357C'),
    ('IoT WiFi 通信モジュール アンテナ内蔵 マルチプロトコル対応 Advanced-9910S'),
    ('環境 SPI接続 センサーモジュール 1.8V動作 分解能16bit RoHS対応 Pro-2600R'),
    ('有線 CAN 通信モジュール 10Gbps メッシュネットワーク対応 ノイズ耐性強化 Industrial-8728S'),
    ('スイッチング 昇圧型 電源IC 出力3A 保護回路内蔵 Pro-4922C'),
    ('絶縁 UART インターフェース Gen5 ESD保護機能付 Industrial-3265S'),
    ('ベンチトップ オシロスコープ デジタル計測器 4CH 4M IoT-3064B'),
    ('温湿度 I2C接続 センサーモジュール 3.3V動作 サンプリング1kHz ノイズ耐性強化 Embedded-3014A'),
    ('産業用 WiFi 通信モジュール 10Gbps 暗号化機能付 ノイズ耐性強化 Advanced-9062R'),
    ('LDO 絶縁型 電源IC 出力1A スタンバイ機能付 RoHS対応'),
    ('ノイズ対策 USB インターフェース Gen4 ESD保護機能付 高信頼性 Embedded-8617C'),
    ('有線 WiFi 通信モジュール 10Gbps 暗号化機能付 高信頼性 Embedded-1195B'),
    ('車載用 省電力 マイコン 64bit メモリ1MB'),
    ('DC-DC 同期整流 電源IC DIP 保護回路内蔵 VCCI Class B 省電力設計 IoT-5729A'),
    ('加速度 SPI接続 センサーモジュール 5V動作 低消費電力1mA以下 IoT-5253C'),
    ('セキュア RS485 通信モジュール 1Gbps 暗号化機能付 長寿命設計 Embedded-5579S'),
    ('高速 UART インターフェース Ver4.0 ホットプラグ対応'),
    ('加速度 I2C接続 センサーモジュール 超小型2mm角 サンプリング10kHz'),
    ('産業用 WiFi 通信モジュール 10Gbps 暗号化機能付'),
    ('AVR 高性能 マイコン 32bit メモリ256KB IoT-3958C'),
    ('IoT Ethernet 通信モジュール 外付け マルチプロトコル対応'),
    ('有線 Ethernet 通信モジュール 1Gbps メッシュネットワーク対応 IoT-4199R'),
    ('有線 CAN 通信モジュール 10Gbps 暗号化機能付 FCC認証取得 IoT-5179B'),
    ('産業用 Ethernet 通信モジュール 10Gbps メッシュネットワーク対応 UL認証取得 Smart-8520R'),
    ('堅牢 DisplayPort インターフェース Gen5 サージ保護付 高信頼性 Smart-1788B'),
    ('加速度 デジタル出力 センサーモジュール 小型3mm角 分解能16bit RoHS対応'),
    ('ジャイロ アナログ出力 センサーモジュール 小型3mm角 サンプリング1kHz EMC対策済'),
    ('ノイズ対策 USB インターフェース Ver4.0 サージ保護付 高信頼性'),
    ('ベンチトップ マルチメータ デジタル計測器 チャンネル2CH メモリ長1M'),
    ('環境 SPI接続 センサーモジュール 3.3V動作 サンプリング1kHz'),
    ('高速 HDMI インターフェース Gen4 ホットプラグ対応'),
    ('加速度 SPI接続 センサーモジュール 超小型2mm角 サンプリング10kHz CE認証取得 Pro-1216A'),
    ('セキュア Bluetooth 通信モジュール 外付け セキュリティ機能搭載 Embedded-9094B'),
    ('ジャイロ 高精度 センサーモジュール 3.3V動作 低消費電力1mA以下 Industrial-5459S'),
    ('ハンディ ロジアナ デジタル計測器 チャンネル2CH サンプリング1GS/s UL認証取得 IoT-5645R'),
    ('ARM 高性能 マイコン 32bit メモリ1MB'),
    ('スイッチング 同期整流 電源IC 出力3A スタンバイ機能付 ノイズ耐性強化 Smart-4434R'),
    ('IoT WiFi 通信モジュール アンテナ内蔵 セキュリティ機能搭載 EMC対策済 Industrial-5739C'),
    ('スイッチング 昇圧型 電源IC パッケージSOP 保護回路内蔵'),
    ('ARM Cortex-M マイコン クロック周波数100MHz メモリ1MB 省電力設計 Industrial-2605S'),
    ('ハンディ マルチメータ デジタル計測器 4CH 2M'),
    ('産業用 Ethernet 通信モジュール 10Gbps 暗号化機能付'),
    ('ノイズ対策 USB インターフェース Gen4 オートネゴシエーション 高信頼性 IoT-1507C'),
    ('LDO 同期整流 電源IC パッケージSOP 効率98% Advanced-7284B'),
    ('AC-DC 降圧型 電源IC 出力5A スタンバイ機能付 FCC認証取得 Advanced-7108B'),
    ('温湿度 デジタル出力 センサーモジュール 超小型2mm角 分解能16bit'),
    ('LDO 昇降圧型 電源IC 出力1A 効率98% Embedded-9605A'),
    ('スイッチング 絶縁型 電源IC QFN 保護回路内蔵 長寿命設計 Industrial-1976A'),
    ('堅牢 DisplayPort インターフェース Gen4 サージ保護付 Pro-9637C'),
    ('環境 アナログ出力 センサーモジュール 5V動作 低消費電力1mA以下'),
    ('温湿度 I2C接続 センサーモジュール 5V動作 分解能24bit'),
    ('絶縁 PCIe インターフェース Ver4.0 ESD保護機能付'),
    ('産業用 USB インターフェース Ver3.0 ホットプラグ対応 UL認証取得'),
    ('ハンディ ロジアナ デジタル計測器 帯域100MHz サンプリング1GS/s'),
    ('ARM 省電力 マイコン 16bit GPIO 100pin 長寿命設計 IoT-5752C'),
    ('LDO 同期整流 電源IC パッケージSOP スタンバイ機能付 Advanced-1389S'),
    ('絶縁 UART インターフェース Gen4 ホットプラグ対応 Advanced-8898C'),
    ('ポータブル スペアナ デジタル計測器 帯域200MHz 4M UL認証取得'),
    ('ARM 省電力 マイコン 400MHz メモリ1MB Embedded-5799C'),
    ('IoT RS485 通信モジュール 1Gbps 暗号化機能付 省電力設計'),
    ('AVR 高性能 マイコン クロック周波数100MHz メモリ256KB RoHS対応 Embedded-7564B'),
    ('車載用 高性能 マイコン 400MHz GPIO 32pin Industrial-8449R'),
    ('ポータブル パワーメータ デジタル計測器 8CH 2GS/s Embedded-5096S'),
    ('ハンディ マルチメータ デジタル計測器 チャンネル2CH 4M'),
    ('高機能 スペアナ デジタル計測器 帯域100MHz サンプリング1GS/s UL認証取得'),
    ('ノイズ対策 USB インターフェース Gen5 ホットプラグ対応 長寿命設計 Advanced-1559R'),
    ('加速度 I2C接続 センサーモジュール 1.8V動作 サンプリング1kHz UL認証取得 Industrial-2875A'),
    ('IoT Bluetooth 通信モジュール 10Gbps 暗号化機能付 UL認証取得'),
    ('堅牢 USB インターフェース Ver4.0 サージ保護付 UL認証取得'),
    ('無線 CAN 通信モジュール 外付け マルチプロトコル対応 UL認証取得 Pro-6896R'),
    ('温湿度 高精度 センサーモジュール 1.8V動作 分解能24bit EMC対策済 IoT-5459S'),
    ('LDO 同期整流 電源IC DIP 入力範囲4-60V Smart-4913S'),
    ('車載用 高性能 マイコン 32bit GPIO 64pin 長寿命設計 Industrial-9130C'),
    ('IoT Ethernet 通信モジュール 1Gbps セキュリティ機能搭載 省電力設計'),
    ('高機能 パワーメータ デジタル計測器 500MHz サンプリング1GS/s'),
    ('リニア 昇圧型 電源IC QFN 効率98% Advanced-8793R'),
    ('堅牢 USB インターフェース Ver2.0 ESD保護機能付 CE認証取得 高信頼性'),
    ('ジャイロ 高精度 センサーモジュール 5V動作 低消費電力1mA以下'),
    ('RISC-V デュアルコア マイコン 64bit メモリ1MB'),
    ('絶縁 USB インターフェース Gen5 ESD保護機能付 Advanced-3308B'),
    ('堅牢 PCIe インターフェース Gen5 サージ保護付 Pro-7981A'),
    ('加速度 高精度 センサーモジュール 5V動作 低消費電力1mA以下 Smart-6817C'),
    ('近接 アナログ出力 センサーモジュール 5V動作 分解能24bit'),
    ('スイッチング 昇降圧型 電源IC パッケージSOP 保護回路内蔵 Embedded-1828B'),
    ('産業用 WiFi 通信モジュール アンテナ内蔵 暗号化機能付'),
    ('LDO 絶縁型 電源IC QFN 入力範囲4-60V'),
    ('ハンディ オシロスコープ デジタル計測器 帯域100MHz 4GS/s Industrial-2290R'),
    ('堅牢 USB インターフェース Ver3.0 ESD保護機能付'),
    ('車載用 Cortex-M マイコン 400MHz GPIO 64pin Industrial-1539A'),
    ('環境 SPI接続 センサーモジュール 小型3mm角 分解能24bit Advanced-7834R'),
    ('産業用 組込み向け マイコン 32bit メモリ256KB FCC認証取得 Industrial-6502S'),
    ('スイッチング 絶縁型 電源IC 出力5A スタンバイ機能付 省電力設計 Advanced-4099B'),
    ('据置 ロジアナ デジタル計測器 500MHz 4M CE認証取得 Embedded-7532S'),
    ('リニア 絶縁型 電源IC パッケージSOP 効率95% IoT-7429C'),
    ('スイッチング 昇降圧型 電源IC 出力3A 入力範囲4-60V'),
    ('ハンディ ロジアナ デジタル計測器 帯域100MHz 2M Embedded-2346S'),
    ('無線 CAN 通信モジュール 10Gbps 暗号化機能付 VCCI Class B ノイズ耐性強化'),
    ('加速度 デジタル出力 センサーモジュール 超小型2mm角 分解能24bit IoT-3751R'),
    ('加速度 高精度 センサーモジュール 小型3mm角 分解能24bit REACH対応 ノイズ耐性強化 Smart-8448B'),
    ('ジャイロ アナログ出力 センサーモジュール 超小型2mm角 サンプリング10kHz'),
    ('スイッチング 同期整流 電源IC DIP 効率98% 省電力設計 Embedded-8098A'),
    ('ポータブル パワーメータ デジタル計測器 チャンネル2CH 4GS/s 高信頼性'),
    ('有線 Ethernet 通信モジュール 10Gbps 暗号化機能付 CE認証取得'),
    ('加速度 デジタル出力 センサーモジュール 小型3mm角 低消費電力1mA以下 IoT-5303R'),
    ('ノイズ対策 UART インターフェース Gen5 オートネゴシエーション Pro-1375A'),
    ('スイッチング 昇降圧型 電源IC 出力1A 効率95% 長寿命設計'),
    ('リニア 降圧型 電源IC QFN スタンバイ機能付'),
    ('ARM 高性能 マイコン 16bit メモリ1MB Embedded-4706S'),
    ('AVR 組込み向け マイコン クロック周波数100MHz GPIO 32pin UL認証取得 Pro-2588S'),
    ('加速度 I2C接続 センサーモジュール 5V動作 分解能16bit IoT-2055B'),
    ('DC-DC 昇降圧型 電源IC パッケージSOP 効率98% Embedded-6343R'),
    ('セキュア CAN 通信モジュール 外付け メッシュネットワーク対応 Embedded-2692S'),
    ('スイッチング 同期整流 電源IC 出力1A 効率98% 省電力設計 Industrial-1135A'),
    ('AVR 省電力 マイコン 400MHz GPIO 64pin UL認証取得 IoT-4344B'),
    ('絶縁 UART インターフェース Gen4 ESD保護機能付 EMC対策済'),
    ('温湿度 高精度 センサーモジュール 1.8V動作 低消費電力1mA以下'),
    ('産業用 組込み向け マイコン 64bit メモリ512KB 高信頼性 IoT-3837S'),
    ('LDO 降圧型 電源IC QFN 効率98% Industrial-6729A'),
    ('LDO 昇圧型 電源IC QFN 入力範囲4-60V RoHS対応 Pro-6015C'),
    ('絶縁 UART インターフェース Gen4 オートネゴシエーション'),
    ('高機能 スペアナ デジタル計測器 チャンネル2CH サンプリング1GS/s Smart-6345C'),
    ('据置 オシロスコープ デジタル計測器 帯域200MHz 4GS/s UL認証取得 Smart-5370R'),
    ('無線 WiFi 通信モジュール 10Gbps セキュリティ機能搭載 Embedded-1604R'),
    ('絶縁 DisplayPort インターフェース Gen5 サージ保護付 CE認証取得 Industrial-5404A'),
    ('リニア 昇圧型 電源IC 出力1A 保護回路内蔵 UL認証取得 長寿命設計 Pro-2504A'),
    ('ノイズ対策 UART インターフェース Ver4.0 サージ保護付 Embedded-2949S'),
    ('ポータブル ロジアナ デジタル計測器 帯域200MHz サンプリング1GS/s FCC認証取得 高信頼性 Smart-2970A'),
    ('RISC-V 高性能 マイコン 32bit メモリ1MB'),
    ('環境 アナログ出力 センサーモジュール 3.3V動作 低消費電力1mA以下 長寿命設計 IoT-9820S'),
    ('産業用 省電力 マイコン 32bit メモリ256KB Pro-7226R'),
    ('加速度 高精度 センサーモジュール 超小型2mm角 サンプリング1kHz EMC対策済 Industrial-2209S'),
    ('産業用 UART インターフェース Gen4 ESD保護機能付 RoHS対応 Pro-4642R'),
    ('環境 I2C接続 センサーモジュール 超小型2mm角 分解能16bit Embedded-4829B'),
    ('RISC-V 組込み向け マイコン クロック周波数100MHz GPIO 32pin'),
    ('ベンチトップ ロジアナ デジタル計測器 4CH メモリ長1M Industrial-5621S'),
    ('DC-DC 同期整流 電源IC QFN 効率98% 高信頼性 IoT-1210R'),
    ('RISC-V デュアルコア マイコン 400MHz GPIO 100pin RoHS対応 Embedded-3060A'),
    ('スイッチング 絶縁型 電源IC 出力1A 効率98%'),
    ('近接 SPI接続 センサーモジュール 小型3mm角 サンプリング1kHz EMC対策済'),
    ('環境 I2C接続 センサーモジュール 1.8V動作 低消費電力1mA以下 IoT-3284S'),
    ('温湿度 I2C接続 センサーモジュール 1.8V動作 サンプリング10kHz VCCI Class B Embedded-7410C'),
    ('高速 DisplayPort インターフェース Gen5 オートネゴシエーション Embedded-9112S'),
    ('無線 Ethernet 通信モジュール 1Gbps マルチプロトコル対応 FCC認証取得 長寿命設計 Smart-8902B'),
    ('ARM 省電力 マイコン 32bit メモリ512KB Embedded-4594A'),
    ('リニア 昇降圧型 電源IC 出力3A 効率98% Pro-6466A'),
    ('ベンチトップ マルチメータ デジタル計測器 8CH 4M FCC認証取得'),
    ('RISC-V 省電力 マイコン 16bit GPIO 100pin FCC認証取得 Smart-8151C'),
    ('加速度 SPI接続 センサーモジュール 1.8V動作 サンプリング1kHz ノイズ耐性強化'),
    ('絶縁 UART インターフェース Ver4.0 ホットプラグ対応 EMC対策済'),
    ('ハンディ スペアナ デジタル計測器 500MHz サンプリング1GS/s Embedded-2758B'),
    ('産業用 DisplayPort インターフェース Gen3 ホットプラグ対応'),
    ('IoT CAN 通信モジュール アンテナ内蔵 暗号化機能付'),
    ('産業用 RS485 通信モジュール 通信速度100Mbps セキュリティ機能搭載'),
    ('セキュア RS485 通信モジュール 通信速度100Mbps 暗号化機能付 Industrial-8188R'),
    ('無線 Bluetooth 通信モジュール 通信速度100Mbps マルチプロトコル対応 EMC対策済'),
    ('LDO 降圧型 電源IC 出力5A 入力範囲4-60V'),
    ('ARM 省電力 マイコン 16bit GPIO 32pin VCCI Class B Smart-5471S'),
    ('有線 CAN 通信モジュール 1Gbps 暗号化機能付'),
    ('RISC-V 組込み向け マイコン クロック周波数100MHz メモリ512KB 省電力設計 Smart-5249B'),
    ('スイッチング 同期整流 電源IC 出力3A 保護回路内蔵'),
    ('産業用 UART インターフェース Ver4.0 ESD保護機能付 FCC認証取得'),
    ('AC-DC 昇降圧型 電源IC QFN 入力範囲4-60V 高信頼性 Smart-1444B'),
    ('スイッチング 昇圧型 電源IC 出力5A 効率98% REACH対応'),
    ('有線 RS485 通信モジュール 1Gbps メッシュネットワーク対応'),
    ('ポータブル スペアナ デジタル計測器 500MHz 4GS/s ノイズ耐性強化 Advanced-5033A'),
    ('産業用 Cortex-M マイコン 200MHz メモリ512KB'),
    ('加速度 高精度 センサーモジュール 超小型2mm角 サンプリング1kHz 高信頼性'),
    ('ベンチトップ ロジアナ デジタル計測器 チャンネル2CH 2M Industrial-5364A'),
    ('産業用 Bluetooth 通信モジュール アンテナ内蔵 セキュリティ機能搭載 VCCI Class B Industrial-7680A');